aws/eks-hybrid

- test/e2e/vpc.go
Instead of hardcoding AZs, use describe-azs api to get the list.
> adds describe-azs when creating subnets for e2e

- hybrid-nodes-cdk/lib/nodeadm-stack.ts
> adds ec describe-azs perm to e2e devstack

- test/e2e/run.go
Stop patching VPC CNI daemonset for hybrid nodes anti-affinity in E2E tests, since the `aws-node` DS now already has the anti-affinity configured during deployment.
> Stop patching VPC CNI daemonset for hybrid nodes anti-affinity

- test/e2e/peered/cluster.go
> uses the right vpc when creating nodes

- hack/e2e-cleanup.sh
Improved the comment in the code to better explain this for next time.  These calls, like roles and a couple others, require a second api call to get the tags. We get the tags to see if the resource is even connected to the cluster we are deleting.  in the case where we are running multiple of these concurrently, with different kube versions, we run into cases where one pulls the resources, then tries to check for the tags which is a retried operation, but by the time it does, the resource has been deleted by the job that should clean it up.
This fixes the iam-ra cleanup to match the other iam resources.
Also slight improvement to the instance deletion and waiting. …
> iam-ra cleanup to handle concurrent deletes

- test/e2e/os/testdata/log-collector.sh
Update log collector script URL since awslabs/amazon-eks-ami#2073 has been merged.
> Update log collector script URL

- test/e2e/ec2/instance.go
When running all the tests concurrently there would usually be a few that would fail to create the instance, even with the 60 retries.  This removes the wrapping of the standard retrier in favor of using more of the defaults and passing a custom iserrorretryable.
> improves instance creation retry

- internal/system/swap.go
When I changed the swap partition checking in #246 I did not realize a version of the code I wrote already existed and was used during actual swap disable.  This PR removes my change and changes the existing code slightly to support the validation phase and the actual disabling.  I did change the existing code to check the err type when opening the /proc/swaps file like in my previous PR.
> improve swap partition checking

- internal/ssm/install.go
While the full tests suite, I have noticed a failure which occurs about every other run, for a test or two.  
It seems mostly related to rhel and I believe its specifically due to the `insights-client` which automatically runs on boot of a rhel node and will attempt to dnf/rpm install a few rhel specific packages.  
This install process appears to line up, sometimes, with our call to ssm install and ends up causing it to fail with
`error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Resource temporarily unavailable)`
This changes adds retries to the ssm install, like we do for [containerd](https://github.com/aws/eks-hybrid/blob/33e2bb92815d748c66a084300a1297557cf2cf47/internal/containerd/install.go#L43) and …
> retry running ssm install to avoid flaky install failures

- test/e2e/cluster/cluster.go
When running all the tests concurrently, we will sometimes get 429 - Too many requests, errors on cluster creation.  This adds retries to this step.
I dont think this is 100% complete.  Even after I changed this, i did exp one other failure where the cluster create was accepted by the eks api, but eks ended up marking its cluster status as `failed`.  I have not been able to repro this to see what else it tells us about the error.  I suspect in that case, we may want to just delete the cluster and try again, but saving that for a future PR/improvement.
Improved the waitForActiveCluster to return the cluster, instead of relying on the creation output.  This allows retuning setup in case something fails. …
> adds retries to cluster creation for e2e setup

- test/e2e/ec2/instance.go
We are crossing the limit of the user data size for rhel9 instances.  This adds gzipping before base64 encoding the user data.  This should buy us some more time until we hit the limit again.
As a future improvement, we could switch user data to be stored as a secret and then downloaded and ran.  We could also change how we use the presigned urls, which is a large chunk of the user data, to instead of being pre generated and stored, generated at the time of use and collected via ssh/ssm instead of via traps like we do now.  The trap/pre-generate approach was needed before we had the jumpbox and ssh available to worker nodes.
By submitting this pull request, I …
> gzips user data for e2e instances

- test/e2e/kubernetes/kubernetes.go
I have seen a handful of failures due to the pod logs check where the log does not contain `nginx`.  I *think* this is because its not fully up yet.  This adds a readiness probe to ensure the nginx is ready to serve traffic and adds a check to the pod ready for the containers ready condition, which includes readiness probes.
I verified if i configured it with a bad http url in the readiness, the e2e test failures waiting for the pod to be ready.
> adds startup probe to nginx e2e pod

- hack/e2e-cleanup.sh
To limit the clusters a single cleanup run will potentially clean up, support passing a prefix with a wildcard such as, to clean up any clusters that start with the prefix.
`nodeadm-canary-1-31-*`
> supports cluster prefix for e2e-cleanup

- hack/e2e-cleanup.sh
There are two ways we run the cleanup script.  Before kicking off any test runs we run it with no cluster name and it goes through and deletes all clusters + resources which are older than 1 day.  After each specific test run, we call it again (after calling the e2e-test cleanup) with the specific cluster name passed as the script argument.  
When running with the cluster name parameter, managed instance resources are only deleted if they have the cluster tag which matches the supplied cluster name.
In the case of running the script with no cluster name supplied, managed instances were cleaned up if their lastpingtime was greater than 1 day.  
We ran into a case in CI where a second test run kicked off while the previous was running. …
> fixes managed instance cleanup to avoid affecting other runs

- test/e2e/os/rhel.go
We noticed while investigation a rhel based failure, which is caused by a kernel [bug](https://access.redhat.com/solutions/7094020), that the AMI's published by the rhel account id can be a couple different versions.  Right now they are still releasing AMIs for 8.8 and 8.10.  Earlier this month a new 8.8 was published and we unknowingly started using and testing that version in our e2e.  
The intention of our tests is to test the most, reasonably, latest version of the OSs as we can.  This PR changes the ami search logic to include the version in deciding if an ami is newer instead of just created date.
By submitting this pull request, I confirm that you can use, …
> fixes rhel ami logic to include major.minor version

- buildspecs/test-nodeadm.yml
- cmd/e2e-test/cleanup/cleanup.go
- cmd/e2e-test/setup/setup.go
- hack/run-e2e.sh
- hybrid-nodes-cdk/lib/constants.ts
- hybrid-nodes-cdk/lib/nodeadm-stack.ts
- test/e2e/cluster/create.go
- test/e2e/cluster/delete.go
- test/e2e/cluster/resolver.go
- test/e2e/credentials/cfn-templates/hybrid-cfn.yaml
- test/e2e/credentials/setup.go
- test/e2e/credentials/stack.go
- test/e2e/peered/setup.go
- test/e2e/resolver.go
- test/e2e/suite/nodeadm_test.go
> add 1.32 to k8s versions slice

- test/e2e/ssm/command.go
The default execution timeout on an ssm runcommand is an hour.  We currently wait for 10 mins for a ssm command to finish.  
Due to an error introduced in nodeadm, we started seeing wait timeouts during the upgrade flow.  When the wait times out after 10 mins, we do not get any of the logs from the running commands which makes debugging the issue more difficult.
This adds an execution timeout of 10 mins to the ssm command which will give us the partial log output from the command.
> adds exec timeout to ssm commands

- test/e2e/credentials/stack.go
We werent deleting the access entry during test cleanup so when running ginkgo a second time it would fail when trying to recreate the access entries.
> fixes delete access entry in e2e

- test/e2e/addon/addon.go
- test/e2e/cluster/create.go
If rerun `e2e-test setup` command in some cases, `CreateAddon` for pod identity would error out because the it's installed during the first command.
```
2025-01-27T09:57:55.733-0600    INFO    Successfully started EKS hybrid cluster
2025-01-27T09:57:55.733-0600    INFO    Create cluster add-on   {"ClusterAddon": "eks-pod-identity-agent"}
{"level":"fatal","ts":1737993476.0275998,"caller":"e2e-test/main.go:36","msg":"Command failed","error":"creating E2E test infrastructure: creating add-on {eks-pod-identity-agent nodeadm-e2e-tests-1-30 {\"daemonsets\":{\"hybrid\":{\"create\": true}}}} for EKS cluster: operation error EKS: CreateAddon, https response error StatusCode: 409, RequestID: c0a6ea0e-17c0-4d84-a3d9-7cb7f6ab02b8, ResourceInUseException: Addon already …
```
> Ignore ResourceInUseException for CreateAddon

- buildspecs/build-nodeadm.yml
> Avoid s3 progress spam when building nodeadm

- ATTRIBUTION.txt
> Update attribution file for nodeadm

- internal/ssm/config.go
> Log SSM instance ID after registration

- internal/flows/install.go
- internal/ssm/source.go
> Log URL of SSM installer

- Makefile
> Update ginkgo CLI version to match go module

- test/e2e/credentials/stack.go
This allows to re-run the e2e cli to setup resources.
> Make setup access entry idempotent

- testdata/nodeconfig.yaml
Remove unused testdata directory.
> Remove unused testdata directory

- internal/containerd/install.go
- internal/packagemanager/packagemanager.go
> refactor: add containerd version parameter

- test/e2e/cluster/stack.go
- test/e2e/credentials/stack.go
- test/e2e/errors/aws.go
> Fix checking for CFN not found error

- test/e2e/cluster/stack.go
> Fix one more instance of stack nto found

- internal/ssm/install.go
- internal/ssm/source.go
- test/integration/cases/install-with-region/run.sh
> Minor edits to --region flag

- test/e2e/cluster/stack.go
We saw a couple failures yesterday due to stack creation and i ran into one in my devstack because i had not deployed a new s3 perm.  In these cases, the current code tries to show the actual create_failed error, but the way the cfn events work is there will be potentially lots of create_failed.  After the first thing fails, the other in progress creations are also marked as failed.  
This change loops thru all events and finds the first create_failed, which i believe is what the cfn ui uses to mark `likely root cause`.
Old output:
```
2025-03-05T22:57:51.298Z    INFO    Waiting for hybrid nodes setup stack to be created  {"stackName": "EKSHybridCI-Arch-nodeadm-e2e-tests-759d11aa-bc5a-4c8e-b091-159ea46557c1"} …
```
> finds more likely root cause for cfn stack error

- test/e2e/peered/cluster.go
Add the adaptiveMode and more retries to describe cluster call.
> adds more retries to e2e test get cluster details

- test/e2e/cleanup/cloudformation.go
> Improve CFN failure reason message

- test/e2e/cluster/cluster.go
- test/e2e/credentials/ssm.go
- test/e2e/peered/cluster.go
- test/e2e/ssm/command.go
- test/e2e/suite/nodeadm_test.go
> Revert "sets retry mode/attempts at aws config level for e2e"

- test/e2e/ssm/command.go
> redacts s3 url when collecting logs

- test/e2e/cleanup/sweeper.go
- test/e2e/cleanup/vpc.go
We ran into this once and added eni cleanup to the bash script. This reimplements that in the new go sweeper.
> adds eni cleanup to go based sweeper

- hack/run-e2e.sh
Fetch cluster and hybrid network parameters from env vars.
> Fetch cluster and hybrid network parameters from env vars

- cmd/e2e-test/cleanup/cleanup.go
- cmd/e2e-test/node/create.go
- cmd/e2e-test/node/delete.go
- cmd/e2e-test/setup/setup.go
- test/e2e/aws.go
- test/e2e/suite/nodeadm_test.go
I missed overriding the region in my pr earlier.
> fixes e2e aws usage

- hybrid-nodes-cdk/lib/nodeadm-stack.ts
> fix rhel username and password typo

- buildspecs/build-nodeadm.yml
- buildspecs/dev-release-nodeadm.yml
Adding a file with git version to release artifacts
> Add git version to release artifacts

- test/e2e/addon/podidentityverify.go
We previously run `aws sts get-caller-identity` to verify test pod for pod identity is functioning before accessing the configured aws resources. However we found in some cases, the command failed to reach to IMDS endpoint, even though the command is retried multiple times.
```
exec aws sts get-caller-identity command on pod awscli-mi-0aa3f3ba93b69a6c3: err: command terminated with exit code 255, stdout:
Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve container metadata: Connect timeout on endpoint URL: "http://169.254.170.23/v1/credentials"
```
Now with this PR, I am moving the check into readiness probe. Basically it increases the retry period and hopefully the …
> Set up readiness probe for pod identity test spec

- test/e2e/kubernetes/kubernetes.go
Both calico and cilium add the NodeNetworkUnavailable condition set to False once the agents fully get running.  We have seen different kinds of flakes that make me think sometimes the cni, calico mainly, are not fully setup since node ready triggers as soon as the cni bin is put on the host.  In cilium's case we use the taint that the operator applies.
Using this condition should be safe, at least for the current versions of calico and cilium we are using.
> adds wait for node NodeNetworkUnavailable condition in e2e

- buildspecs/prod-release-nodeadm.yml
- buildspecs/prod-release-test.yml
Adding release buildspecs for nodeadm and testing artifacts
> Add prod nodeadm and test release buildspecs

- test/e2e/cluster/cfn-templates/setup-cfn.yaml
This PR improves tag value for name to distinguish between cluster and hybrid node
Tested locally
> Refactor: improve tag value for name to distinguish between cluster and hybrid node

- test/e2e/cluster/cluster.go
Very rarely, but we sometimes see that the cluster takes longer than 30 minutes to be active.
In addition we now print the number of retries to make sure we are actually retrying and it's not that a request is getting stuck.
> Increase wait for cluster active timeout

- test/e2e/README.md
Wanted to document the typical flow I use when running the tests locally and some of the design principles we have tried to follow.
> adds readme for e2e testing

- hybrid-nodes-cdk/lib/nodeadm-stack.ts
We shortened the prefix but forgot to change the perm.
> fixes podid prefix in devstack role policy

- test/e2e/kubernetes/node.go
Weve seen flakes when draining/cordoning nodes. This wraps the operations in retry.
> adds retry around drain and cordon in e2e

- test/e2e/cluster/cluster.go
> Improve error handling when cluster not active

- test/e2e/suite/flaky_code.go
- test/e2e/suite/nodeadm_test.go
Currently when an Expect failures in a ginkgo test the error is not actually logged until the defer cleanups are run. Since we use these extensively it makes our logs a bit hard to follow.
This adds a customer fail handler to log the error message before forwarding to ginkgo's default Fail handler.  The flakyCode block complicated this a bit since it was relying on the global Fail, now the failhandler is passed in from the test so it can call our custom one instead.
> adds error message logging before ginkgo running defer cleanups

- test/e2e/cluster/stack.go
This avoid waiting for the stack to update when rerunning setup, when its not needed.
> avoids updating creation time in e2e stack

- test/e2e/cleanup/eks.go
If a cluster has a update in progress the delete will fail. This adds a wait for the cluster to become active again before deleting.
Created a cluster, changed remote node config to trigger an update, ran cleanup.
> adds wait for cluster active before deleting

- test/e2e/suite/nodeadm_test.go
Keeping the matching infra in place in case we need to disable other tests in the future.
> enables iam-ra on older OSs

- test/e2e/suite/nodeadm_test.go
> Revert "enables iam-ra on older OSs"

- internal/packagemanager/packagemanager.go
> Refresh metadata cache after installing docker repo

- cmd/nodeadm/install/install.go
- internal/creds/validation.go
- internal/creds/validation_test.go
- internal/system/os.go
> Revert "Remove validation blocking rhel8 and ubuntu2004 in nodeadm"

- test/e2e/cleanup/eks.go
We think there are internal updates happening on these clusters when the delete fails with ResourceInUse. Adding more logging to see if there is any indication in the cluster/updates.
> adds more logging when deleting cluster fails

- internal/node/pods.go
- internal/node/pods_test.go
- internal/node/validations.go
- internal/node/validations_wb_test.go
> Reduce node validation unit test duration

- test/e2e/suite/nodeadm_test.go
> Revert "Revert "enables iam-ra on older OSs""

- buildspecs/cleanup-nodeadm.yml
- buildspecs/test-nodeadm.yml
- hack/run-e2e.sh
> supports eks custom endpoints for run-e2e.sh

- buildspecs/prod-release-nodeadm.yml
Removing ACLs from production buckets.
> Remove public acls from prod bucket

- buildspecs/prod-release-nodeadm.yml
Changing from symlink style to uploads from local.
> Fix updating symlinks on prod release spec

- cmd/e2e-test/ssh/ssh.go
Changes ssh subcommand to accept instance id or name. This makes it a bit easier to create a node and ssh in, without having to track down the instance id.
> changes e2e-test ssh to accept instance name

- test/e2e/cleanup/sweeper.go
- test/e2e/credentials/stack.go
We had this working at one point but at some point broke it due to not creating the iamra-role (which is by design), but still trying to create the access entry.
Also added similar check in the sweeper code.
> fixes SKIP_IRA_TEST flag in setup and sweeper

- cmd/e2e-test/node/create.go
Since #363 , we have to wait for node to be ready and then create routes for the ec2 instance when running `node create` command. Otherwise we'll see the following error. The flag becomes useless thus I am removing it in this PR.
```
❯ ./_bin/e2e-test node create -c ssm -f e2e-param.yaml -o ubuntu2404 -a amd64 nvidia-6
2025-04-29T15:07:25.067-0700	INFO	Updating hybrid nodes stack	{"stackName": "EKSHybridCI-nodeadm-e2e-tests"}
2025-04-29T15:07:25.180-0700	INFO	No updates are to be performed for hybrid nodes stack	{"stackName": "EKSHybridCI-nodeadm-e2e-tests"}
2025-04-29T15:07:25.217-0700	INFO	E2E resources stack deployed successfully	{"stackName": "EKSHybridCI-nodeadm-e2e-tests"}
2025-04-29T15:07:25.217-0700	INFO	Creating access entry …
```
> Remove waitForReady flag in node create command

- internal/aws/ecr/ecr.go
> add new region for ecr images

- buildspecs/prod-release-nodeadm.yml
- hack/release-nodeadm.sh
- hack/validate-release.sh
Fix latest path symlinks for nodeadm prod release.
> Fix latest paths for prod nodeadm release

- test/e2e/addon/podidentityverify.go
We occasionally see the following failures in canary tests due to network glitch.
```
[FAILED] With OS al23-amd64 and with Credential Provider ssm
Expected pod identity add-on should be created successfully
Expected success, but got an error:
<*fmt.wrapError | 0xc0007120a0>: 
deleting the awscli pod awscli-mi-07e390d6dcd135b01: deleting pod: Delete "https://f9ed6590634c7f068f3efa66c7db2e50.yl4.eu-north-1.eks.amazonaws.com/api/v1/namespaces/default/pods/awscli-mi-07e390d6dcd135b01": dial tcp 16.16.11.186:443: i/o timeout
{
msg: "deleting the awscli pod awscli-mi-07e390d6dcd135b01: deleting pod: Delete \"[https://F9ED6590634C7F068F3EFA66C7DB2E50.yl4.eu-north-1.eks.amazonaws.com/api/v1/namespaces/default/pods/awscli-mi-07e390d6dcd135b01\](https://f9ed6590634c7f068f3ef …
```
> Move pod identity deletion into defer block

- internal/test/context.go
> Add helper for timed context in tests

- internal/retry/retry.go
- internal/retry/retry_test.go
This allows us to increase the total timeout for the generic network retrier and ensure we drop requests that are taking too long and probably have been dropped.
> Add retry option for a per request timeout

- test/e2e/cleanup/cloudwatchlogs.go
When implementing the cw cleanup, I had intended to only delete groups 15 days or older.  I missed that in the case of sweeping a specific cluster-name, which we do in the canary after a test run, on success or error, it was deleting the group.  This was kind of defeating the purpose of enabling cluster logging....
This fixes this behavior by checking the age threshold before calling the generic helper which ignores the age if its a cluster-name match.
> fixs cwlogs cleanup during sweeper --cluster-name

- test/e2e/cluster/create.go
Add retries when looking for CloudWatch log groups
Added a retry mechanism that keeps checking for CloudWatch log groups until they're found or until 5 minutes pass. This fixes issues where the code would fail because it couldn't find log groups that were still being created.
> Add retries for tagging Cluster log groups

- test/e2e/cluster/cfn-templates/setup-cfn.yaml
- test/e2e/cluster/stack.go
- test/e2e/securitygroup/ingress.go
> Revert "Revert "security group ingress cluster setup template""

- hack/run-e2e.sh
- hybrid-nodes-cdk/lib/nodeadm-stack.ts
We have addon test suite now but we haven't set up the pipeline for it yet.
Set up addons pipeline e2e tests. 
> Set up addon test suite pipeline

- test/e2e/ssm/command.go
When running multiple pipelines concurrently, we sometimes see throttle exceptions which end up failing the test. This "attempts" to workaround this by increase the number of retries and the max back off time.  We may see more test timeouts if commands end up retrying or waiting this long, but that results a failure just like it would now.
> increases ssm waits/timeout

- hack/validate-release-artifacts.sh
We ran into an issue on prod where the S3 folder when `ls-d` was returning "folder" keys in addition to object keys which the script does not expect. This change switches to use the s3api so we can filter out the 0 size objects, which are the directory placeholders.
When running on my mac the ordering wasnt consistent between the hardcoded expected list and the list returned from s3. Added a sort to ensure on a given host both list are sorted the same.
Just to be extra safe, added checks for empty expected/actual file list to ensure we would catch that case if it were to happen.
By submitting this pull request, I confirm that you can use, modify, copy, and …
> improves artifact validation script for release

- test/e2e/addon/nodemonitoringagent.go
- test/e2e/addon/prometheus.go
- test/e2e/kubernetes/daemonset.go
- test/e2e/suite/addon_ec2.go
- test/e2e/suite/addons/addons_test.go
Added:
- DaemonSetWaitForReady 
- Prometheus test flow
> prometheus test

- hybrid-nodes-cdk/lib/constants.ts
> Remove 1.26 and add 1.33 in cdk constants

- test/integration/cases/init-with-config-enrichment/run.sh
- test/integration/cases/init-with-iam-custom-cert-path/run.sh
- test/integration/cases/init-with-node-ip-validation/run.sh
- test/integration/cases/init-with-ssm/run.sh
- test/integration/cases/init-with-swap-partition/run.sh
- test/integration/cases/install-containerd-source-none/run.sh
- test/integration/cases/install-with-iam/run.sh
- test/integration/cases/install-with-region/run.sh
- test/integration/cases/install-with-ssm/run.sh
- test/integration/cases/install-with-timeout/run.sh
- test/integration/cases/uninstall-with-force/run.sh
- test/integration/cases/uninstall-with-source-none/run.sh
- test/integration/cases/upgrade-with-iam/run.sh
- test/integration/cases/upgrade-with-source-none/run.sh
- test/integration/cases/upgrade-with-ssm/run.sh
- test/integration/infra/Dockerfile
- test/integration/test-constants.sh
> Move supported versions to a constants file for integration tests

- cmd/e2e-test/node/create.go
- test/e2e/peered/network.go
- test/e2e/suite/test_node.go
> move DisableSourceDestCheck

- test/e2e/ec2/routes.go
```
[FAILED] With OS al23-amd64 and with Credential Provider iam-ra
Expected EC2 route to pod CIDR should have been created successfully
Expected success, but got an error:
<*fmt.wrapError | 0xc000854be0>: 
adding routes for node pod CIDRs: adding route for node pod CIDR 10.2.0.0/24: could not create route to instance i-0c6a348e43e3fad28 for dst CIDR 10.2.0.0/24: operation error EC2: CreateRoute, https response error StatusCode: 400, RequestID: bf568420-483c-4693-8b94-a6e672ced0ed, api error IncorrectInstanceState: Instance with state 'unknown-running' is not valid for this operation.
```
We think this could be due to us adding/removing routes during test runs.  Allowing this error to be retried to give the ec2 api a chance to eventually …
> adds retries for creating e2e node routes

- internal/flows/uninstall.go
Set Adaptive Retry Mode in SSM Client with 30 second max backoff
> adaptive retry mode on uninstall ssm client

- cmd/nodeadm/debug/debug.go
- cmd/nodeadm/init/init.go
- cmd/nodeadm/upgrade/upgrade.go
- internal/system/swap.go
- internal/system/swap_test.go
- internal/system/swap_validator.go
- internal/system/swap_validator_test.go
- test/integration/run.sh
Add validations for swap disablement to nodeadm debug command
> Add validations for swap disablement

- test/e2e/addon/certmanager.go
- test/e2e/addon/nodemonitoringagent.go
- test/e2e/addon/nvidiadeviceplugin.go
- test/e2e/nodeadm.go
- test/e2e/os/amazonlinux.go
- test/e2e/os/bottlerocket.go
- test/e2e/os/rhel.go
- test/e2e/os/ubuntu.go
- test/e2e/peered/node.go
- test/e2e/suite/addon_ec2.go
- test/e2e/suite/addons/addons_test.go
- test/e2e/suite/peered_vpc.go
Adding Bottlerocket to addons test suite.
```
Ran 12 of 12 Specs in 868.950 seconds
--
SUCCESS! -- 12 Passed | 0 Failed | 0 Pending | 0 Skipped
Ginkgo ran 1 suite in 14m29.036849214s
Test Suite Passed
```
> Add Bottlerocket to addons test suite

- test/e2e/peered/network.go
When re-running the E2E tests with ginkgo, we run into this issue:
```console
[FAILED] EC2 route to pod CIDR should have been created successfully
Expected success, but got an error:
<*fmt.wrapError | 0x14000f4a400>: 
adding routes for node pod CIDRs: adding route for node pod CIDR 10.87.0.0/24: could not create route to instance i-0afccb9e3bc3a3177 for dst CIDR 10.87.0.0/24: operation error EC2: CreateRoute, https response error StatusCode: 400, RequestID: 292c04a0-1840-4671-b118-4177690ee3a0, api error RouteAlreadyExists: The route identified by 10.87.0.0/24 already exists.
```
This PR fixes it by skipping adding the CIDR to the route table if it already exists in the table.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> Skip adding CIDR block to route table if it already exists

- hybrid-nodes-cdk/lib/nodeadm-stack.ts
Add ECR Public authorization token retrieval permissions.
> Add ECR Public authorization token retrieval permissions

- test/e2e/cluster/cfn-templates/setup-cfn.yaml
> fix yaml indentation

- test/e2e/addon/podidentityresource.go
- test/e2e/addon/podidentityverify.go
- test/e2e/suite/addon_ec2.go
- test/e2e/suite/addons/addons_test.go
> fix pod identity role getter

- test/e2e/addon/podidentityresource.go
> fix pod identity role identification

- test/e2e/suite/mixed_mode/mixed_mode_test.go
This fixes a cleanup issue in mixed mode e2e tests where the test labels aren't propagated to other test runs after being initialized in `SynchronizedBeforeSuite`. This helps prevent the labelselector from being empty during cleanup.
> Used SharedTestData for mixed mode test setup

- test/e2e/suite/mixed_mode/mixed_mode_test.go
Moves cleanup to global pre-test execution instead of before each individual test case, and adds individual test labels. This prevents test cases from cleaning up resources from other test cases during parallel execution.
> Add individual test labels to mixed-mode test infrastructure

- internal/node/hybrid/aws.go
We are seeing the following issue when running `nodeadm uninstall` in SSM based EKS hybrid nodes. 
```
$ sudo ./nodeadm uninstall
{"level":"info","ts":"2025-07-24T13:51:09.143Z","caller":"uninstall/uninstall.go:74","msg":"Loading installed components"}
{"level":"info","ts":"2025-07-24T13:51:09.143Z","caller":"uninstall/uninstall.go:83","msg":"Creating daemon manager.."}
{"level":"info","ts":"2025-07-24T13:51:09.147Z","caller":"uninstall/uninstall.go:97","msg":"Validating if node has been drained..."}
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
```
It errors out when `nodeadm` sends the request to API server to list pods on the node but fails due to `NoCredentialProviders` error. During code review, I found it's caused by the following code snippet. …
> Set AWS_SHARED_CREDENTIALS_FILE env var only if credential path exists when building kube client

- cmd/e2e-test/ssh/ssh.go
node `ssh` command fails for Ubuntu, AL, RHEL nodes.
```
❯ ./_bin/e2e-test ssh i-0db5154e378626abd
Starting session with SessionId: jupeng-Isengard-5zo8eisx57lejknqbpdufbr4c8
Warning: Permanently added '10.1.1.138' (ED25519) to the list of known hosts.
ec2-user@10.1.1.138: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Exiting session with sessionId: jupeng-Isengard-5zo8eisx57lejknqbpdufbr4c8.
```
The issue was introduced by BottleRocket e2e test, which modifies the ssh command to use `ec2-user` as the user. However, our regular OS (Ubuntu, RHEL, AL), does not have these users when it's provisioned. Thus ssh command failed. 
Now it will check what OS image it is. If it's bottlerocket, then it uses ec2-user for ssh command. Otherwise, it would default …
> Fix e2e test ssh command error for regular OS

- test/e2e/os/testdata/rhel/8/cloud-init.txt
- test/e2e/os/testdata/rhel/9/cloud-init.txt
> Create symlink for CloudWatch addon compatibility on rhel

- test/e2e/addon/pcaissuer.go
> wait until issuer is ready

- test/e2e/addon/addon.go
- test/e2e/addon/cloudwatch.go
- test/e2e/addon/externaldns.go
- test/e2e/addon/nvidiadeviceplugin.go
- test/e2e/addon/podidentityaddon.go
- test/e2e/addon/podidentityverify.go
- test/e2e/addon/s3csidriver.go
Replace const `namespace ` with `defaultNamespace` to improve readability for addon package
build successfully
> refactor: Replace namespace const with defaultNamespace to improve readability for addon package

- hybrid-nodes-cdk/lib/nodeadm/policies.ts
> add permissions for nodegroups

- hybrid-nodes-cdk/lib/nodeadm-stack.ts
This pr is to add nodeadm-mixed-mode pipleline to HybridNodesCdkStack 
Adds createMixedModePipeline() method to deploy mixed_mode.test suite
alongside existing e2e test pipelines in HybridNodesCdkStack 
###
> add mixed mode pipeline to CDK stack

- test/e2e/addon/podidentityaddon.go
> Add retries for pod identity sa creation

- test/e2e/addon/podidentityaddon.go
> update the version
