test/e2e/cfn-templates/hybrid-cfn.yaml
test/e2e/stack.go
test/e2e/vpc.go

Some region (ap-southeast-5 for example) does not support IAM Roles Anywhere. We will need to skip creating IRA resources when setting up e2e test on those region.
We need to use a template with condition to only create IRA resource when the region supports IRA because it will cause template parsing error in those region if IRA resource exists in template.
`Unrecognized resource types: [AWS::RolesAnywhere::Profile, AWS::RolesAnywhere::TrustAnchor]`

Skip creating IRA resources in e2e on region that does not support IRA

---

test/e2e/nodeadm.go
test/e2e/os/amazonlinux.go
test/e2e/os/arch.go
test/e2e/os/rhel.go
test/e2e/os/ubuntu.go
test/e2e/suite/nodeadm_test.go

Create a method that returns the EC2 instance type that will be used in e2e test based region and OS architecture and remove the InstanceType definition in all OS packages.
Built e2e.test binary and ran test on a cluster on ap-southeast-5 region, an EC2 of type m6i.large was created and e2e test passed.

Set ec2 instance type based on region and arch

---

.gitignore
test/e2e/aws.go
test/e2e/credentials/setup.go
test/e2e/peered/cluster.go
test/e2e/suite/nodeadm_test.go

Next refactor piece after separating test code from "library". This PR focuses on the tests setup code, making some pieces reusable when possible and when not, splitting the long setup functions into smaller logic units. Most of that code is boiler plate, so by just moving it to separate functions with meaningful names we make reading the test code top to bottom easier.
In addition, a couple minor improvements/cleanups, that don't really change the flow of the test:
* Simplify the code that reads cluster details for a Hybrid cluster. Now it can infer all the data from just the cluster name by querying AWS APIs.
* Moved all that code to use go SDK v2. Eventually we should move all of it, but it's ok to do it piece meal.
* Now the `skipCleanup` is a flag that gets passed from the suite …

Refactor e2e suite and tests setup

---

hack/e2e-cleanup.sh
hybrid-nodes-cdk/lib/nodeadm-stack.ts

We have noticed cases where a sg will block a vpc from being deleted. This 
- adds sg cleanup
- waits for instances and peering connection deletion
- failsafe cleanup for igws

adds cleanup for vpc sgs

---

test/e2e/os/amazonlinux.go
test/e2e/os/arch.go
test/e2e/os/rhel.go
test/e2e/os/ubuntu.go

This PR fixes the instance type assignment based on architecture. Earlier we were only checking if the architecture was `x86_64` to assign an AMD64 instance type, and otherwise assigning ARM64 if the check fails, but Ubuntu uses `amd64` and so the check was failing, leading to us using an ARM64 instance type for an AMD64 AMI which led to the error
```console
The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again.
```
Now we are checking for both `amd64` and `x86_64` when assigning instance types.

Fix instance type assignment based on architecture

---

Makefile
doc/api.md

The previous crd-ref-docs has a memory issue when generating docs.
```
2024-12-10T15:29:39.731-0800	INFO	crd-ref-docs	Loading configuration	{"path": "../eks-hybrid/doc/config.yaml"}
2024-12-10T15:29:39.733-0800	INFO	crd-ref-docs	Processing source directory	{"directory": "../eks-hybrid/api/", "depth": 6}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1007b4164]
goroutine 120 [running]:
go/types.(*Checker).handleBailout(0x14000c461c0, 0x14000c1bd38)
/opt/homebrew/Cellar/go/1.23.3/libexec/src/go/types/check.go:404 +0x9c
panic({0x100e10b40?, 0x1013e8a30?}) …
```

Upgrade crd-ref-docs version to fix memory issue when generating doc

---

hack/run-e2e.sh

Add --no-color flag when running ginkgo so the ginkgo output does not contain characters like [3m for color rendering

Add --no-color flag when running ginkgo

---

Makefile

The GOLANGCI_LINT is defined after the lint target, which means that is empty if you only run make lint. If you haven't downloaded the binary before, this won't try to download the binary and will fail.
We could have instead moved the whole development block, but that also affects the order in which we show the blocks in the help. And I think development makes more sense at the top since it's more important. The other option wad to define the GOLANGCI_LINT variable at the top, but then we lose the nice encapsulation of having it defined in the build section with the targets that need it.

Fix make lint target

---

test/e2e/os/amazonlinux.go
test/e2e/os/arch.go
test/e2e/os/rhel.go
test/e2e/os/ubuntu.go

We have probably overgrew the original architecture abstraction and we end ended up using it for multiple things. The differences between the ami arch name between OS made the code prone to errors and required having a lot of context to modify safely.

Normalize OS architecture

---

hack/e2e-cleanup.sh
hybrid-nodes-cdk/lib/nodeadm-stack.ts
test/e2e/credentials/stack.go

We werent cleaning up the roles anywhere trust anchors and profiles. This adds it to the cleanup script.  
- Normalized tag key casing, since these apis do not match ALL the others in their casing...
- Cleaned up some comments
- Skip iam-ra cleanup on ap-southeast-5 which does not support this api.  We should probably change this to be an env var that is set in the canary to make disabling this easier per region.

adds iam-ra profiles/trust-anchors to cleanup

---

test/e2e/credentials/stack.go

If running test with skip_cleanup, the second run will fail because we were passing the wrong string.

fixes e2e cfn update flow

---

test/e2e/os/testdata/ubuntu/2404/cloud-init.txt

Ubuntu pushed a new containerd, 1.7.19+really1.7.12-0ubuntu4.2, to 2404 this week.  This version includes the app armor fix. We can remove this workaround from our tests and docs.

removes ubuntu 2404 apparmor fix

---

test/e2e/os/arch.go

I don't think we need to use such a large instance for these tests. Dropping this down until we see otherwise.

drops the e2e node instance size

---

test/e2e/credentials/stack.go

Fix issue with creating IRA resource.
Check if SKIP_IRA_TEST is set to true and only create IRA resources if the value is not true.

Fix issue with creating IRA resource

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
internal/kubelet/config.go
internal/ssm/daemon.go
internal/ssm/install.go
test/e2e/aws.go
test/e2e/credentials/certificate.go
test/e2e/os/arch.go
test/e2e/os/ubuntu.go
test/e2e/ssm/command.go
test/e2e/suite/nodeadm_test.go

Just ran the `golangci-lint` and fixed all issues (for the linters we have enabled). I separated the changes with one lint error per commit for easier review.
Now we run the linter globally and not only on new changes. This avoids issues being introduced by two PRs merging without being aware of each other.
As a bonus, I fixed the linter config since it was using deprecated fields.

Fix linter errors

---

test/e2e/kubernetes/kubernetes.go
test/e2e/suite/nodeadm_test.go

Adds a "kubectl" logs and exec to the nginx pod during the join test. This validates that the automatic cert approval is working since these both require a valid kubelet serving cert.

adds exec and logs to join e2e test

---

internal/system/swap.go
test/integration/.dockerignore
test/integration/cases/init-with-swap-partition/config.yaml
test/integration/cases/init-with-swap-partition/run.sh
test/integration/cases/init-with-swap-partition/swaps-file
test/integration/cases/init-with-swap-partition/swaps-partition
test/integration/infra/.dockerignore
test/integration/infra/Dockerfile
test/integration/infra/Dockerfile.dockerignore

If nodeadm detects a swap partition, it errors out to the user to disable that.  If its a file, it can remove/disable it.  The logic that checked for this was exec swapon/awk.  This changes the code to be more like kubeadm's preflight check.  Added a new integration test to validate this.
Improved integration tests docker setup:
- fixed the dockerignore location/paths
- use public ecr golang image from eksd
- pull mock metadata built artifact instead of go install
- copy go.mod/sum and run download to improve rerun caching

improves swap partition checking

---

hack/e2e-cleanup.sh
hybrid-nodes-cdk/lib/constants.ts

When running on al2's bash this syntax will fail due to the missing declare.  Changed dev stack to use al2 image for cleanup job.

fixes cleanup script running on al2's bash

---

example/hybrid-eks-cfn.yaml

An EKS Cluster supporting Hybrid Nodes requires a security group that allows port 443 from those cidrs. This commit adds a secondary security group for those cidrs.
This replaces the SecurityGroupId parameter with a required VpcId that the SecurityGroup will be created in.

Added a SecurityGroup for RemoteNode and RemotePod

---

buildspecs/ecr-cache.yml
test/e2e/kubernetes/kubernetes.go
test/e2e/suite/nodeadm_test.go

The build account now has the nginx image in the regional ecr repos, like the other CNI images.  This changes the test to use the region ecr instead of public ecr.

use region ecr for nginx container

---

test/e2e/kubernetes/kubernetes.go
test/e2e/suite/nodeadm_test.go

When running all the tests concurrently there was generally a failure in some tests due to nodes being cordoned and drained, but would error out during upgrade due to pods running on the node.  We think this is due to cordon taking some time to fully taint the node and with our tests constantly draining nodes, the cilium/calico operator will be rescheduled often and was triggering this failure.
This adds a wait to ensure the node has the proper taint before attempting to drain the node.

waits for cordon to complete

---

test/e2e/os/testdata/log-collector.sh

Now we can invoke log collector script with the `eks_hybrid` flag, which will avoid IMDS collection and queries for AWS region and EC2 instance ID.

Invoke log collector script with eks_hybrid flag

---

internal/containerd/daemon.go
internal/node/ec2/daemons.go
internal/node/hybrid/daemons.go

We added WaitForStatus for the SSM agent [install](https://github.com/aws/eks-hybrid/blob/a78d6765835e19fd2cb873832676a87f5f75c2d3/internal/ssm/daemon.go#L78) because we were running into issues where we would try to use the AWS creds before ssm had been fully activated.
We have a similar case with containerd, where after installing we attempt to pull the sandbox image.  The first time this image is pulled it will usually fail because containerd is not fully running, but this usually fixes itself by the second attempt.  
I have noticed 1 test failure due to this where containerd had not come up before the sandbox pull retries were exhausted, which is only 3 right now.
Adding a WaitForStatus here will solve both:
- the annoying "error" …

adds wait for containerd service

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml

Ran into an issue in the ap-southeast-5 region where this GetAtt syntax was invalid for InstanceId for some reason, works in all other regions.  We can just use Ref against the instance directly which returns the default resource id, which for Instance is the Id.
Side note, we dont even use these cfn outputs... leaving them for now, but we may eventually want to just get rid of them if we dont need them.

use ref instead getatt for instanceid in setup stack

---

internal/artifact/install.go
internal/containerd/install.go
internal/iptables/iptables.go
internal/packagemanager/packagemanager.go
internal/ssm/install.go

We added retries for installing containerd/iptables previously, but I have seen a couple e2e failures due to failure to install yum-utils on rhel, since we need it to register the docker repo to install containerd/runc.  
This adds the retries to all the package installs (yum-utils, ca-certs) and adds a UninstallWithRetries method for all package removals.

adds retries to package install/uninstalls

---

test/e2e/kubernetes/kubernetes.go

I added a startup [probe](https://github.com/aws/eks-hybrid/pull/273) to the nginx pod, but the timeout is too tight. We already have a timeout defined when checking for the pod status, so using that for the startup probe as well.
Side note: The most often case i've seen this be an issue is during upgrades where we remove containerd, but do not remove the running pods nor do we remove the etc/cni.d folder. This results in the upgraded node being ready almost immediately even tho the cni pod is actually going to need to restart after containerd is reinstalled.  I have a future PR to improve this.
By submitting this pull request, I confirm that you can use, modify, …

increases e2e nginx pod startup probe

---

test/e2e/nodeadm.go
test/e2e/nodeadm/commands.go
test/e2e/os/testdata/log-collector.sh
test/e2e/os/testdata/nodeadm-init.sh
test/e2e/suite/nodeadm_test.go

Now that we are using the jumpbox to run remote commands on the worker nodes we can simplify the log collection.  
We used to rely on running the collection in traps in each "bash" script we ran since during some of our phases we may "break" the ec2 ssm, or in the case of cloud-init its just running during booth, to ensure we could capture as many logs, as often as we could.  Now, as long the node boots, we can rely on the jumpbox and ssh to be able to run the log collector.
This also removes the extract complexity around pre generating the links and using them by name, with a fallback.
Now the logs are only collected in the deferCleanup, on failure or success.
By …

changes e2e log collection to happen only once

---

test/e2e/cluster/cluster.go

Notice a few failures in CI due to clusters taking longer than 15 mins to create. Based on the cloudtrail logs it seems like the cluster did in fact eventually go active so increasing the timeout here may improve stability. 

increases e2e cluster wait timeout to 30 minutes

---

Makefile
buildspecs/build-nodeadm.yml
buildspecs/dev-release-nodeadm.yml
hack/run-e2e.sh

Cross build the e2e test binaries (e2e-test is the bin responsible for running setup/clean and e2e.test is the bin which contains the compiled ginkgo tests) and include ginkgo in the artifacts bucket.  This is to be used by the canaries to avoid having to download ginkgo each time and break the arch dependency between the build instance and the canary runner.
Installing ginkgo with go install introduces a bit of weirdness when doing "compilation", but I have commented the code for future me who almost def be confused when i read this in next week!
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

adds cross builds for the e2e bins and ginkgo

---

Makefile

Avoid glibc version mismatches between al2 and al23.

statically compiles ginkgo for e2e tests

---

test/e2e/ec2/instance.go
test/e2e/kubernetes/verify.go
test/e2e/nodeadm/uninstall.go
test/e2e/nodeadm/upgrade.go
test/e2e/peered/node.go
test/e2e/suite/nodeadm_test.go

This cleans up a bit the test specs by moving some of the previously called `***Test` "services" out of the suite package. The goal is to make the tests easier to follow (by hiding the low level details of how each action is executed) and even more importantly, to make this actions reusable from other tests/suites.
I renamed them a bit, switching the abstraction from "tests" to "actions". They live in `kubernetes`, `nodeadm` or `peered` depending if the action is purely a kubernetes API based process or if it includes running nodeadm commands/flows or if is specific to running in a peered VPC.
Ran this manually for one provider-os with the init and upgrade flows.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Cleanup e2e test specs

---

test/e2e/cni/calico.go
test/e2e/cni/cilium.go

Saw a handful of errors relating to creating the CNI manifests. This adds retries using the client-go retry util.  All errors are intentionally retried, using the DefaultRetry config, which is up to 5 times.

retries cni manifests creation in e2e

---

cmd/e2e-test/cleanup/cleanup.go
cmd/e2e-test/main.go
cmd/e2e-test/setup/setup.go
cmd/e2e-test/ssh/ssh.go
test/e2e/peered/jumpbox.go
test/e2e/peered/setup.go

This just leverages the mechanism used by the e2e tests themselves to get a shell into a e2e node. In order to not expose SSH to the internet in those nodes and since SSM is not reliable, we leverage SSM in a separate machine and use to jump to the target machine.
```
❯ ./_bin/e2e-test ssh -h
ssh - SSH into a E2E Hybrid Node running in the peered VPC
Usage:
ssh [INSTANCE_ID]
Positional Variables:
INSTANCE_ID   The instance ID of the node to SSH into (Required)
Flags:
--version   Displays the program version string.
-h --help      Displays help with available flag, subcommand, and positional value parameters.
```
```
❯ ./_bin/e2e-test ssh i-0b123c4z90db123cf
Starting session with SessionId: mysession
Warning: Permanently added '10.1.1.127' (ED25519) to the list of known hosts.
,     #_
~\_ …
```

Add command to ssh into e2e peered nodes

---

test/e2e/kubernetes/kubernetes.go
test/e2e/kubernetes/verify.go

We saw a few connection timeout errors when trying to exec and get pod logs.  Adding retries, with default retry config (5 retries, 10ms backoff).

retries exec and logs in e2e test

---

cmd/nodeadm/config/root.go
cmd/nodeadm/debug/debug.go
cmd/nodeadm/init/init.go
cmd/nodeadm/install/install.go
cmd/nodeadm/main.go
cmd/nodeadm/uninstall/uninstall.go
cmd/nodeadm/upgrade/upgrade.go
internal/cli/help.go

_Issue #, if available:_ 2817
_Description of changes:_
For each nodeadm command, add example usage and link to nodeadm documentation when using --help.
_Testing (if applicable):_
Validated output for all CLI commands.
_Documentation added/planned (if applicable):_ 
Example:
```
> nodeadm install -h
install - Install components required to join an EKS cluster
Usage:
nodeadm install [KUBERNETES_VERSION]
Positional Variables:
KUBERNETES_VERSION   The major[.minor[.patch]] version of Kubernetes to install (Required)
Flags:
--version               Displays the program version string.
-h --help                  Displays help with available flag, subcommand, and positional value parameters.
-p --credential-provider   Credential process to install. Allowed values are ssm & iam-ra.
-s …
```

Show link to docs when using nodeadm --help

---

go.mod
test/e2e/credentials/stack.go

We noticed a case where the cloudformation stack failed to create because the anywhere profile creation appears to take a bit longer than ssm gives to try and get the tags for that profile.  The current method was already idempotent so this adds 1 retry to attempt to resolve the issue without failing the test.

adds retry to test stack deployment

---

test/e2e/peered/node.go
test/e2e/suite/nodeadm_test.go

When ctrl-c cancelling a ginkgo run, it was not properly cancelling the running actions because the context we passed to the test was new per test. This change uses the ginkgo ctx which allows for running actions to know that the ctx was cancelled.  This also sets the timeout on the defercleanup and the log collecting.

improves context usage for e2e tests

---

cmd/nodeadm/init/init.go
internal/flows/install.go

Unable to run `nodeadm install` within a docker container. D-Bus connection fails due to lack of fully operational systemd:
```
INFO {“level”:“fatal”,“ts”:1736533734.779155,“caller”:“./main.go:53”,“msg”:“Command failed”,“error”:“please install systemd unit file for containerd: dial unix /run/systemd/private: connect: no such file or directory”,“stacktrace”:“main.main\n\t./main.go:53\nruntime.main\n\truntime/proc.go:272”}
INFO The command ‘/bin/sh -c /opt/nodeadmutil/bin/nodeadm install -p iam-ra 1.31.0’ returned a non-zero code: 1
```
Relocate containerd validation from `nodeadm install` to `nodeadm init`.
N/A
By submitting this pull request, I confirm that you can …

refactor: validate containerd daemon during init, not install

---

test/e2e/cluster/cluster.go

In cases where the cluster status goes to failed it would be helpful to get the describe cluster output to see if that leads us to any potential root causes/fixes.  We already return the cluster from waitFor even when there is an error.

logs the cluster on failure

---

cmd/nodeadm/main.go
cmd/nodeadm/uninstall/uninstall.go
internal/flows/uninstall.go
internal/packagemanager/packagemanager.go

*Issue #, if available:* 2746
*Description of changes:* 
Removes the docker repo fetched by the package manager upon uninstall when the original containerd-source was 'docker'. 
Tested on Ubuntu for apt and CentOS for yum. 
- Verified that repo is correctly deleted and `apt install containerd.io` and `yum install containerd.io` no longer finds package after nodeadm uninstall.
- Checked that the docker repo is untouched upon uninstall if not originally installed by nodeadm

Remove containerd docker repo on uninstall

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/cluster/create.go
test/e2e/cluster/delete.go
test/e2e/cluster/stack.go
test/e2e/peered/keypair.go
test/e2e/peered/setup.go

Noticed a couple odd failures today in differnet regions due to cfn outputs.  I dont know for sure that cfn is the issue, but weve one like this before so im assuming a bit here.  Either way, this change pulls the jumpboxid and keypairid using the api instead of relying on them from cfn outputs.

changes e2e setup stack to not rely on cfn outputs

---

test/e2e/cluster/stack.go
test/e2e/ssm/command.go

After the setup stack is created, we run an ssm command on the jumpbox to download and verify the ssh private key.  This adds a wait until the instance is registered with SSM to ensure we do not try to run the command, and fail, too soon.

adds wait for instance to be registered with ssm

---

cmd/nodeadm/install/install.go
internal/flows/install.go

A new change caused the package manager configuration for the containerd docker repo to be removed upon uninstallation. Since the upgrade process runs the uninstall process and then the install process, this led to the upgrade process no longer being able to find the containerd package using the docker source, as the package manager was only configured on nodeadm install command and not as part of the install flow. 
**Note that the timeout no longer applies to this process of installing/configuring the docker repo for the package manager; this should be changed in the future.**
Tested on an Ubuntu hybrid node and verified install, init, upgrade, and uninstall commands work as intended.
*Documentation …

fix: always configure package manager prior to package install

---

cmd/nodeadm/uninstall/uninstall.go
cmd/nodeadm/upgrade/upgrade.go
internal/node/pods.go
internal/node/validations.go
internal/node/validations_wb_test.go

We were hiding the real error and assuming that if failed, it meant there were not drained pods. Now he handle differently execution errors from the node not being drained, and return a different error depending on the case.
Tested with e2e upgrade test for al23 and iam-ra

Improve error handling for node drained validation

---

test/e2e/logger.go
test/e2e/suite/nodeadm_test.go

We use the ginkgo no-color option when running tests on CI. This avoids terminal control characters to appear in the logs. However, this only controls the logs emitted by ginkgo and not the one we print. As a result, all the "INFO" log lines showed up mangled in CI logs.

Respect no-color option in e2e test logger

---

buildspecs/test-nodeadm.yml
hack/run-e2e.sh

This makes a bit easier to track the failed tests in the console. It allows to search by status, test name, etc. You can see the logs of each test separately but they tend to be truncated. It might help with metrics as well, but we will see. Either way, it's a cheap change.
This is how it looks:

Add JUnit reports to e2e tests

---

cmd/nodeadm/install/install.go
go.mod
go.sum
internal/flows/install.go
internal/ssm/install.go
internal/ssm/source.go
test/integration/cases/install-with-region/expected-nodeadm-tracker
test/integration/cases/install-with-region/run.sh
test/integration/helpers.sh

*Issue #, if available:* 2906
Add a --region flag to `nodeadm install`, which will determine which region the SSM installer is downloaded from. 
Tested on ubuntu hybrid node and verified :
- original behavior unchanged when no --region flag used
- region flag changes download location (verified through logging output)
- error is handled appropriately for bad region input by checking download url
Flag will be added to public documentation ahead of nodeadm release.

Add region flag to install

---

hack/SKIPPED_TESTS.yaml
test/e2e/credentials/rolesanywhere.go
test/e2e/os/rhel.go
test/e2e/os/ubuntu.go
test/e2e/suite/matcher.go
test/e2e/suite/nodeadm_test.go

Combinations like ubuntu 2004 or RHEL8 and IAM-RA are not supported. Instead of requiring those test to be skipped (they will always fail), we just don't define the test at all.

Don't define e2e specs for not supported configs

---

test/e2e/peered/node.go
test/e2e/suite/nodeadm_test.go

Quality of life improvement when debugging tests. The URl was already printed at the top of the test, but this just also puts it close to the error itself.

Print S3 logs URL when tests fail at init or upgrade

---

hybrid-nodes-cdk/lib/nodeadm-stack.ts
test/e2e/cluster/stack.go

When the CFN stack hits a failure and starts rolling back, it usually records the reason for the failure. So we include this in the stacktrace to get an idea as to why the stack deployment failed. 

Include CFN stack failure reason if available

---

cmd/nodeadm/debug/debug.go
internal/validation/reader.go

This is useful when running it in some automated/background process where there is no terminal to interpret the escape sequences and ends up obfuscating the output.
once this is released, we'll update the scripts we run in the e2e test nodes to use this flag and get a cleaner output.

Add option for no color in debug command output

---

test/e2e/addon/addon.go
test/e2e/addon/podidentityaddon.go
test/e2e/addon/podidentityverify.go
test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/cluster/create.go
test/e2e/cluster/stack.go
test/e2e/kubernetes/kubernetes.go
test/e2e/suite/nodeadm_test.go

This is part 2 of setting up E2E tests for pod identity. [Part 1 PR](https://github.com/aws/eks-hybrid/pull/282)
This PR covers pod identity association setup. 
*(Since this PR already contains enough changes, I will create another PR to actually deploy pods and verify EKS Pod Identity volume is correctly attached.)*
I followed this [public document](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-association.html#_create_a_pod_identity_association_cli) to set up pod identity association.
In summary, the following is required in order to set up pod identity association.
1. Create IAM role with trust relationship for Pod Identity role. The role should also be able to access some AWS resource.
2. Create a service account dedicated …

Set up pod identity association in E2E tests

---

cmd/nodeadm/install/install.go
internal/creds/validation.go
internal/creds/validation_test.go
internal/system/os.go
test/e2e/os/rhel.go

Validate the credential provider during install phase. Both Ubuntu 20 and RHEL 8, ship with lower version of GLIBC which doesn't work with iam-roles-anywhere. 
Also has an improvement to the pagination function used with ec2:DescribeImages API in the E2E test.

Validate credential provider during install

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml

We are seeing intermittent issues on tests when calling `aws` CLI to download SSH key pair on the jumpbox
```
2025-02-17T21:47:22.024Z	[34mINFO[0m	Stdout: Problem downloading private key from ssm!	1739829048904
EVENTS	1739829052825	2025/02/17 21:50:48         	            		1739829048904
EVENTS	1739829052825	2025/02/17 21:50:48         	            	2025-02-17T21:47:22.024Z	[34mINFO[0m	Stderr: 	1739829048904
EVENTS	1739829052825	2025/02/17 21:50:48         	            	You must specify a region. You can also configure your region by running "aws configure".	1739829048904
EVENTS	1739829052825	2025/02/17 21:50:48         	            	failed to run commands: exit status 1	1739829048904
EVENTS	1739829052825	2025/02/17 21:50:48 …
```

Set AWS region when fetching the jumpbox SSH keypair 

---

cmd/e2e-test/cleanup/cleanup.go
cmd/e2e-test/main.go
cmd/e2e-test/node/create.go
cmd/e2e-test/node/delete.go
cmd/e2e-test/node/node.go
cmd/e2e-test/setup/setup.go
cmd/e2e-test/ssh/ssh.go
test/e2e/credentials/stack.go
test/e2e/peered/node.go
test/e2e/s3/urls.go
test/e2e/suite/config.go
test/e2e/suite/nodeadm_test.go

Useful when manually testing or investigating.
```
./_bin/e2e-test node create -h
create - Create a Hybrid Node
Usage:
create [INSTANCE_NAME]
Positional Variables:
INSTANCE_NAME   Name of the instance to create. (Required)
Flags:
--version          Displays the program version string.
-h --help             Displays help with available flag, subcommand, and positional value parameters.
-f --config-file      Path tests config file.
-c --creds-provider   Credentials provider to use (iam-ra, ssm).
-o --os               OS to use (al23, ubuntu2004, ubuntu2204, ubuntu2404, rhel8, rhel9). (default: al23)
-a --arch             Architecture to use (amd64, arm64). (default: amd64)
-w --wait-for-ready   Wait for the node to be ready.
```
```
./_bin/e2e-test node delete -h …
```

Add e2e test commands for manually creating a deleting a node

---

test/e2e/os/testdata/amazonlinux/2023/cloud-init.txt

The eks log-collector script will collect standard log files, such as [/var/log/messages](https://github.com/awslabs/amazon-eks-ami/blob/main/log-collector-script/linux/eks-log-collector.sh). In al23, this file is not created by default like it was in al2.  Following this [guide](https://repost.aws/knowledge-center/ec2-linux-al2023-find-log-files), its fairly simple to enable rsyslog and have it create this file which would then be captured in our log bundle.
An alternative, future improvement, would be to somehow generate this during the log collection script so its more consistent between al2 and al23.
By submitting this pull request, I confirm that you can use, …

adds rsyslog to al23 instances in e2e

---

test/e2e/ec2/instance.go

We are seeing some tests fail with node not being ready. The logs fail to collect on that node as well. 
This PR adds another log that prints the instance health status in case of such failures.

Log ec2 DescribeInstanceStatus for failed nodes

---

internal/firewall/firewalld.go
internal/system/ports.go
test/integration/cases/hybrid-node-system-aspects/run.sh

Nodeadm during init would look if firewall is enabled and if it is, it will setup firewall rules to make sure node can operate properly. It opens up ports for Kubelet, Kube-proxy as well as node ports. 
Depending on the OS nodeadm checks for ufw and firewalld states for configuring the different firewall rules. Sometimes the backing firewall service may not be running or failing and nodeadm init process would just fail. With this change, nodeadm checks if firewall is enabled, it its not, or if theres any error in checking for the firewall state, nodeadm skips setting up the rules and moves on with the init process.
An example log
```
{"level":"warn","ts":1739568835.7944512,"caller":"system/ports.go:50","msg":"Failed to get firewall status","error":"exit status …
```

Set firewall rules on best effort basis

---

example/hybrid-ira-cfn.yaml
example/hybrid-ssm-cfn.yaml
hybrid-nodes-cdk/lib/nodeadm-stack.ts
test/e2e/addon/addon.go
test/e2e/addon/podidentityaddon.go
test/e2e/addon/podidentityverify.go
test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/cluster/create.go
test/e2e/cluster/delete.go
test/e2e/cluster/stack.go
test/e2e/credentials/cfn-templates/hybrid-cfn.yaml
test/e2e/kubernetes/kubernetes.go
test/e2e/suite/nodeadm_test.go

This is part 3 of setting up E2E tests for pod identity. 
[part 1](https://github.com/aws/eks-hybrid/pull/282)
[part 2](https://github.com/aws/eks-hybrid/pull/329)
This PR would create a test pod with a service account, which is associated with pod identity. It then downloads test file from S3 bucket within the test pod. 
[Ref doc](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html)

Create test pod to verify it can access AWS resources with pod identity add-on

---

test/e2e/nodeadm.go
test/e2e/os/testdata/amazonlinux/2023/cloud-init.txt
test/e2e/os/testdata/nodeadm-init.sh
test/e2e/os/testdata/rhel/8/cloud-init.txt
test/e2e/os/testdata/rhel/9/cloud-init.txt
test/e2e/os/testdata/ubuntu/2004/cloud-init.txt
test/e2e/os/testdata/ubuntu/2204/cloud-init.txt
test/e2e/os/testdata/ubuntu/2404/cloud-init.txt
test/e2e/peered/node.go

With the latest release of nodeadm, we can pass the `--region` flag to the install command to specify where to download the ssm install setup from.  This adds that new flag to our cloud-init scripts for the e2e tests.

addds --region flag to nodeadm install during e2e

---

test/e2e/errors/type.go

If we take an empty interface, the errors.As receives as such instead of as the original type passed to our helper. Since all errors can be assigned to an empty interface, our helper always returns true. By making the function take a generic type we both ensure that errors.As receives the right type as well as enforcing that our helper only takes types that implement error, which is required by errors.As.

Fix bug on errors.IsType helper

---

test/e2e/addon/addon.go
test/e2e/addon/podidentityaddon.go

`Errors.IsType()` seems not working as expected. 
Create `Errors.IsAWSErr()` to correctly identify aws err type.
I have the following test code in `addon.go` and manually trigger `ResourcesInUseException` by running node setup twice.
```go
import (
"errors"
e2eErrors "github.com/aws/eks-hybrid/test/e2e/errors"
)
func (a Addon) Create(ctx context.Context, client *eks.Client, logger logr.Logger) error {
logger.Info("Create cluster add-on", "ClusterAddon", a.Name)
params := &eks.CreateAddonInput{
ClusterName:         &a.Cluster,
AddonName:           &a.Name,
ConfigurationValues: &a.Configuration,
}
_, err := client.CreateAddon(ctx, params)
logger.Info("errors.Is", "ResourceInUseException", errors.Is(err, &types.ResourceInUseException{})) …
```

Fix error cast for ResourcesInUseException in addon package

---

cmd/e2e-test/ssh/ssh.go
go.mod

When using the ssh command, its really easy to ctrl-c, like to cancel a bad typing or reverse search and that currently kills the session.  This adds the signal trapping so we can forward it to the process without killing it.  To exit, use either the `exit` command or ctrl-d, which matches the standard the ssh behavior.

adds signal handling to e2e ssh command

---

test/e2e/addon/podidentitybucket.go
test/e2e/addon/podidentityverify.go
test/e2e/cluster/stack.go
test/e2e/kubernetes/kubernetes.go
test/e2e/suite/nodeadm_test.go

Ran into a few issues while testing locally with the new pod identity test:
- We want e2e-test cleanup to be able to be run multiple times and not fail out due to resources already being cleaned up.  I removed the code in the stack.go:delete which relied on the stack information to find the bucket. Instead move the code from nodeadm_test into a helper, similar to the way we handle the jumpbox, and use that during the test and the delete.
- The test was failing for me locally, which ended up being due to having left around buckets from previous test clusters, i use the same cluster name.  I added more steps to the test to try and pinpoint where the issue was. This ended up being that since i had multiple buckets, the code would pick one …

improves e2e pod identity debugging

---

cmd/nodeadm/upgrade/upgrade.go
internal/artifact/install.go
internal/artifact/install_test.go
internal/artifact/package.go
internal/artifact/testdata/dummyfile
internal/artifact/upgrade.go
internal/artifact/upgrade_test.go
internal/cni/install.go
internal/containerd/install.go
internal/flows/init.go
internal/flows/upgrade.go
internal/iamauthenticator/install.go
internal/iamrolesanywhere/install.go
internal/imagecredentialprovider/install.go
internal/iptables/iptables.go
internal/kubectl/install.go
internal/kubelet/daemon.go
internal/kubelet/install.go
internal/packagemanager/packagemanager.go
internal/ssm/daemon.go
internal/ssm/install.go
test/integration/cases/upgrade-with-iam/run.sh
test/integration/cases/upgrade-with-ssm/run.sh
test/integration/helpers.sh
test/integration/infra/Dockerfile

Upgrade today runs an uninstall followed by install + init. While this does achieve upgrade this run operations that might not be required. With this change upgrade operation will check if a particular artifact is due for an upgrade and then only upgrade the artifact. 
Callouts with this change
- cni-plugins ship as tarball so its not possible to check if there is really an upgrade for the plugins. We always upgrade the plugins with this change.
- Similar situation with the SSM installer cli, which doesnt publish its checksums in order for us to validate it. (Future task to add checksums to manifest that will enable us to do this. The installer is also regional)
- For packages installed from OS's package manager, we run the yum/apt upgrade command which will only …

Upgrade improvements - Only upgrade artifacts and services if there is an upgrade avilable

---

test/e2e/cluster/cluster.go
test/e2e/credentials/ssm.go
test/e2e/peered/cluster.go
test/e2e/ssm/command.go
test/e2e/suite/nodeadm_test.go

Instead of configuring retries per request, set the mode and attempts on the config which will apply to all clients created via that config.

sets retry mode/attempts at aws config level for e2e

---

test/e2e/cleanup/s3.go

Missed a place in cleanup where checking for the NoSuchBucket error. The SDK does not return the actual type, the helper checks for the proper errorcode.

ignore correct nosuchbucket error for s3 cleanup

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/cluster/stack.go
test/e2e/peered/jumpbox.go

We have hit a few issues where the jumpbox can not be found when starting the test.  This could be because the instances has not reach the running status or it could be that the instance never boots.
Changing the describeinstance call to use an instance waiter which will loop until the instance is running.
CFN also supports creationpolicy signals for instance creation.  `cfn-signal` is included in the al23 AMI and it calls back to the cfn api to signal that the instance is up and ready.  If this signal does not come within the timeout, cfn will delete and recreate the instance.  This coupled with https://github.com/aws/eks-hybrid/pull/396 should make the stack creation resilient to instance boot failures. …

adds wait for jumpbox to e2e infra stack

---

test/e2e/kubernetes/kubernetes.go

We try to retry all kube requests in case of flaky http failures. We missed this spot when creating the service account.

add retries to sa creation in e2e for podid addon

---

Makefile

When running `ginkgo` test locally, I saw the following prompt. 
```
❯ ./_bin/ginkgo -v -tags=e2e --label-filter="al23-amd64 && ssm && simpleflow" ./test/e2e/suite -- -filepath=/Users/jupeng/workplace/eks-hybrid/e2e-param.yaml
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
Ginkgo CLI Version:
2.22.2
Mismatched package versions found:
2.23.0 used by suite
Ginkgo will continue to attempt to run but you may see errors (including flag
parsing errors) and should either update your go.mod or your version of the
Ginkgo CLI to match.
To install the matching version of the CLI run
go install github.com/onsi/ginkgo/v2/ginkgo
from a path that contains a go.mod file.  Alternatively you …
```

Update ginkgo version

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/cluster/create.go
test/e2e/cluster/stack.go
test/e2e/credentials/stack.go

We were already retrying the cred stack, adding same pattern to infra stack.  We ran into a race creating the routes due to the attachment not being ready, adding dependson should avoid the race.

adds retries to infra stack and dependson for attachements

---

api/v1alpha1/nodeconfig_types.go
crds/node.eks.aws_nodeconfigs.yaml
doc/api.md

Fix documentation for `enableCredentialsFile` config field, to be written from the POV of enabling the option.

Fix documentation for enableCredentialsFile option

---

cmd/e2e-test/cleanup/cleanup.go
cmd/e2e-test/node/create.go
cmd/e2e-test/node/delete.go
cmd/e2e-test/setup/setup.go
cmd/e2e-test/ssh/ssh.go
cmd/e2e-test/sweeper/sweeper.go
test/e2e/aws.go
test/e2e/suite/nodeadm_test.go

Changes all the places we load the aws config in the e2e flows to use the same helper to avoid inconsistent retry settings.

standardizes the loading of the aws config for e2e

---

cmd/e2e-test/node/create.go
cmd/e2e-test/node/delete.go
test/e2e/config.go
test/e2e/peered/serial.go
test/e2e/suite/nodeadm_test.go

We want to try and limit the usage of ginkgo + types in the test/e2e/suite package. This moves a bit of the code around to achieve that.

limits ginkgo imports to e2e/suite

---

internal/iamrolesanywhere/aws_config.go
internal/iamrolesanywhere/aws_config.tpl
internal/iamrolesanywhere/aws_config_test.go

IAM-RA uses aws_signing_helper binary which requires an explicit `--with-proxy` flag to be set if we expect the binary to consume the proxy env vars. This changes checks if proxy env vars are set and adds the flag.

Add proxy flags to IAM-RA

---

test/integration/cases/init-with-config-enrichment/config.yaml
test/integration/cases/init-with-config-enrichment/run.sh
test/integration/docs/patching-moto.md
test/integration/helpers.sh
test/integration/infra/Dockerfile

When working on a new debug command validation, I wanted to validate that config enrichment worked during that command flow.  I realized we did not have any integration test that mocked the eks api.  
This adds a new test, more so as an example since our e2e tests validation config enrichment, that shows how to mock the eks api, with iam-ra, and validates that if the ca/remoteconfig/apiendpoint arent supplied via the config, they are pulled from the eks api.
We needed a [fix](https://github.com/getmoto/moto/pull/8710) to moto due to moto's handling of timestamp types for eks clusters, but there was already a PR open which merged today.  For now, the second commit, installs moto from a specific commit has. Once there is a new release we …

adds new integration test mocking eks api

---

test/e2e/peered/node.go

Log instanceID when creating EC2 instace for hybrid testing
Currently when running hybrid test, it does not output instance ID for EC2, which is not convenient, especially in scenarios that we want to ssh into the EC2 instance for some inspection. We can of course find out the instance ID using aws console but it is annoying.

Log instanceID when creating EC2 instace for hybrid testing

---

test/e2e/kubernetes/kubernetes.go

We are seeing a sporadic issue that pod identity fails to get aws credentials although we have implemented retry strategy.  
```
exec aws sts get-caller-identity command on pod awscli-mi-0aa3f3ba93b69a6c3: err: command terminated with exit code 255, stdout:
Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve container metadata: Connect timeout on endpoint URL: "http://169.254.170.23/v1/credentials"
```
So far we have no clue why this happens. In this PR, I am changing `retry.DefaultRetry` to `retry.DefaultBackoff` in `ExecPodWithRetries` so that it can wait a bit more time when retrying the pod exec command.
*Documentation added/planned (if …

Use DefaultBackoff retry for ExecPodWithRetries

---

test/e2e/addon/podidentityverify.go

Fine tune timeoutSeconds and periodSeconds to improve reliability for pod identity test.
Default timeoutSeconds is 1 so our probe considers the command execution `aws sts get-caller-identity` failed if it does not receive response within 1 seconds. However this is a remote call, which can takes more than 1 seconds to complete. Without this change, current setting for probe causes pod in `NotReady` state.   
Manually triggered the CI in dev stack and it succeeded multiple times. 

Set timeoutSeconds and periodSeconds for readiness probe

---

internal/node/hybrid/ip_validator_test.go
test/integration/cases/init-with-node-ip-validation/config-ip-in-range.yaml
test/integration/cases/init-with-node-ip-validation/config-ip-out-of-range.yaml
test/integration/cases/init-with-node-ip-validation/run.sh

Adds an integration test for `node-ip-validation` init flag and updates the unit test with passing node-ip validation flag so that the test case includes a DNS record; this ensures that the --node-ip flag value is used first

test: add integration test for ip-validation

---

buildspecs/ecr-cache.yml
test/e2e/addon/podidentityverify.go
test/e2e/suite/nodeadm_test.go

Match nginx and cni images by using regional ecr repos.

use regional ecr for awscli image

---

cmd/e2e-test/node/create.go
cmd/e2e-test/node/delete.go
test/e2e/addon/podidentityverify.go
test/e2e/constants/constants.go
test/e2e/kubernetes/node.go
test/e2e/kubernetes/verify.go
test/e2e/nodeadm/uninstall.go
test/e2e/nodeadm/upgrade.go
test/e2e/peered/node.go
test/e2e/suite/nodeadm_test.go

Adds a new label to the created kubenetes nodes in the e2e tests.  This label will be used to detect when the node joins the instead of the internal IP.  
We have seen cases where it appears that the node joins and gets ready, but it is never found by the internalip.  This does include a check when the node joins, validating the joined internal IP with the instance IP.  For now, this will still fail the test, but may gave us a clue into what is causing this discrepancy. 
The instanceName is used, instead of the nodeName because the created ec2.Instance via peeredNode, has the instanceName instead of the nodeName. Using the instanceName made it easier to grab the correct value in the various places throughout the test.  Not opposed to use …

add e2e-label to kube node to detect joining

---

test/e2e/cluster/cluster.go
test/e2e/cluster/create.go

We can remove the dep on the aws cli from the e2e flow if we generate the kubeconfig manually instead of exec-ing out.  This uses the client go config struct and writing to create the kubeconfig based on the eks cluster data

uses sdk to create kubeconfig instead of aws cli for e2e

---

test/e2e/addon/podidentityverify.go
test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/cluster/stack.go

With the previous code there was a chance of collision between stacks if their UUIDs started with the same segment. Now we use the full UUID so collisions should not happen.

Improve pod identity bucket name

---

test/e2e/addon/podidentitybucket.go
test/e2e/cleanup/eks.go
test/e2e/cleanup/s3.go
test/e2e/cleanup/vpc.go
test/e2e/errors/aws.go
test/e2e/errors/type.go

We are seeing cases where the pre test sweeper is running to try and find old resources. Since s3 buckets require a second call to get the tags, we currently check for bucketnotexist when getting tags to handle the case where the bucket is deleted between the call of getting the buckets and the call to get the tags.  This changes now handles the opposite case where the bucket is created but the tagging is done yet.
Also added a check for a 403 when trying to delete the cluster, which happens when using the CI role which is limited by tags if the cluster is already deleted.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

ignore NoSuchTagSet when finding s3 buckets to cleanup

---

cmd/e2e-test/rune2e/command.go
test/e2e/run/e2e.go
test/e2e/run/runner.go

We want to try and ensure cleanup and reporting always happens.  There are cases where the test setup/tests themselves can run too long and trigger the overall canary timeout. In those cases we do not get the result json nor do we cleanup the infra.  
This adds deadlines to the various contexts to try and ensure we always have time to run the final steps.

adds context deadlines for run-e2e flow

---

internal/flows/uninstall.go
internal/kubelet/install.go
internal/kubelet/install_test.go

Remove the kubelet cert on uninstall to avoid ever trying to use an old cert if nodeadm init is ran again on the same node against a different cluster.
part 1 of #413 

removes kubelet cert on uninstall

---

test/e2e/run/report.go

In ginkgo's output json, beforesuite/defercleanup are included in the "specs" and if they fail will show up in the "failedtest" slice and ultimately included in the slack message.  Leaving that for now, but improving the test count to only include `It`s which are the actual test in the numbers.  If we see lots of slack messages with the before/after stuff included in the failed tests and its confusing for people, we can look at rendering those differently.  

only count Its in TestFailed counter

---

cmd/nodeadm/uninstall/uninstall.go
internal/flows/uninstall.go
internal/ssm/aws.go
internal/ssm/config.go
internal/ssm/install.go
internal/ssm/install_test.go
internal/ssm/registration.go
test/integration/cases/init-with-ssm/config.yaml
test/integration/cases/init-with-ssm/run.sh
test/integration/helpers.sh

Weve seen an issue in our e2e tests where when a node rejoins, after running uninstall, ssm can sometimes take a few iterations of its cred refresh loop to get the new creds for the newly activated hybrid node.  While this is happening, kubelet has already exec'd iam-auth to get creds which are for the previous hybrid activation, which is still valid.  These valid creds are cached, but the kubelet cant use them to register itself because its using the old nodes creds.
This removes the aws config file and symlink that we create for ssm to ensure that on uninstall, the creds are all removed and cant be reused after reinstalling. 
By submitting this pull request, I …

removes aws config and ssm symlink on uninstall

---

internal/artifact/source.go
internal/aws/source.go
internal/cni/install.go
internal/cni/install_test.go
internal/flows/install.go
internal/iamauthenticator/install.go
internal/iamauthenticator/install_test.go
internal/iamrolesanywhere/install.go
internal/iamrolesanywhere/install_test.go
internal/imagecredentialprovider/install.go
internal/imagecredentialprovider/install_test.go
internal/kubectl/install.go
internal/kubectl/install_test.go
internal/kubelet/install.go
internal/kubelet/install_test.go
internal/test/install.go

When adding gpg validation to ssm, I added retries around both the downloading and the checksum validation to catch cases where the checksum fails due to a bad download.  I actually saw something like this in 1 test run in my devstack.
This PR changes the remaining artifact downloading to match this pattern where checksum validation can trigger a retry.
Note:
The new unit tests are basically the same between the different artifacts.

adds retries around install artifacts if checksums fail

---

test/e2e/suite/nodeadm_test.go

Ran into a instance in my dev account where a instance never got to the running state. This makes that expectation retryable within the flakycode handler.

retries instance running waiter timeout in e2e

---

internal/node/pods.go
internal/node/pods_test.go
internal/node/validations.go
internal/node/validations_wb_test.go

add retries for node validations

---

.github/workflows/golangci-lint.yml
.golangci.yml
internal/aws/ec2/instance_waiter.go
internal/containerd/install.go
internal/ssm/install_test.go
internal/validation/reader_test.go
test/e2e/addon/podidentitybucket.go
test/e2e/cluster/stack.go
test/e2e/kubernetes/node.go
test/e2e/kubernetes/pod.go
test/e2e/os/ubuntu.go
test/e2e/ssm/command.go
test/e2e/suite/flaky_code.go

I noticed the open https://github.com/aws/eks-hybrid/pull/434 bumping to the newer github action for golint, but it fails because we are still on v1 of golangci-lint.
This PR updates to v2. I ran the `golangci-lint migrate` to generate the new config file.  There were some newly triggered code lint issues, this could be because the config is not exactly like it was before or the defaults have changed.  I updated the ones i felt were minor (error messages ending in ., using switch instead of if, using replaceall, skipping composed struct keys).  I disabled:
- '-ST1001' # ST1001: should not use dot imports - since we use this for gomega/gingko
- '-ST1005' # ST1005: error strings should not be capitalized - we have a few places in nodeadm …

updates golangci-lint to v2

---

test/e2e/cleanup/eks.go

*Description of changes:* Increases timeout to 8 mins to reduce chance of timeout due to slow cluster deletion

Increase deleteClusterTimeout for e2e stack cleanup to 8 mins

---

cmd/nodeadm/uninstall/uninstall.go
internal/cleanup/cleanup.go
internal/cleanup/cleanup_test.go
test/integration/cases/uninstall-with-force/run.sh

Adds a new  flag to the  command that enables additional cleanup of leftover directories from the node process. This is useful when a complete cleanup is needed, such as when repurposing a node or troubleshooting persistent issues.
The cleanup is opt-in to prevent accidental deletion of user data in these directories, as they may contain custom configurations or other important files that should be preserved by default.

Add force flag to nodeadm uninstall

---

test/e2e/constants/constants.go
test/e2e/suite/nodeadm_test.go
test/e2e/suite/peered_vpc.go
test/e2e/suite/test_node.go

This is an attempt to break out some of the init and upgrade test code that is the same between the two.  Introduced a new TestNode struct to make setup/verify a bit cleaner between the two test.  Moved the peeredVPCTest out into its own file to try and limit nodeadm_test.go to just be the "two" test cases.

introduces helpers for common blocks of nodeadm e2e tests

---

test/e2e/cleanup/eks.go

Bump up cluster create and delete timeouts to 15 min

Bump up cluster create and delete timeouts to 15 min

---

internal/iamrolesanywhere/daemon.go

When enabling iam-ra service, we write the systemd file but dont refresh the systemd metadata. Subsequent start requests would fail without reloading daemons.

Refresh systemd after adding iam-ra unit file

---

internal/kubernetes/unauthenticated.go
internal/kubernetes/unauthenticated_test.go

Older Kubernetes versions returned 403, with 1.32 now it returns 401.

Accept both 403 and 401 when making unauth request

---

test/e2e/cleanup/ssm.go

We ran into a case where we deleted an instance right after it was created in another test because the LastPingDate was not set yet and default date is 1/1/0000

changes ssm managed instnace cleanup to use register date

---

buildspecs/prod-release-nodeadm.yml

Prod release spec has variable expansion on echo which is not supported on buildspecs. 

Fix prod-buildpsec to avoid variable expansion

---

test/e2e/nodeadm/commands.go
test/e2e/os/testdata/nodeadm-init.sh
test/e2e/suite/test_node.go

We have been running `nodeadm debug` at the end of the cloud-init in our e2e tests. The exit code has been ignored.
We recently found that one of the validations only works for 1.28+ and another one that broke in 1.32.  This change moves the debug call to after the node has joined (or timed out) and will fail the test if the debug command returns a non-zero exit code.

fails e2e if debug command fails

---

cmd/e2e-test/cleanup/cleanup.go
cmd/e2e-test/rune2e/command.go
cmd/e2e-test/setup/setup.go
cmd/e2e-test/sweeper/sweeper.go
test/e2e/run/e2e.go
test/e2e/suite/nodeadm_test.go
test/e2e/suite/peered_vpc.go

This is useful when debugging calls in cloudtrail, specially for concurrent runs and conflicts with cleanups.

Add different user-agent for the e2e test pieces

---

internal/cli/logger.go

Although perhaps easier to parse, timestamps in epoch is almos unreadable. ISO8601 should make easier to debug timing issues.
In addition, I find quite annoying to have the stacktrace on the fatal print line and the end when the command files because this is captured where Fatal is called and not where the error originated. Hence, it's always "main.go.....runtime/proc.go...". This is useless and creates noise when trying to figure out what the actual error is.

Print logs with readable time and disable stack

---

ATTRIBUTION.txt
buildspecs/build-nodeadm.yml
buildspecs/test-nodeadm.yml

We have multiple pipelines that re-use the build stage/buildspec, which uploads the binaries to s3 buckets. These are later used in the test stages. Due to having multiple build stages, the binaries get overwritten during test stage and could result in faulty test results. This change seperate the logic where build stage only builds and passes on the binaries to the next stages. The test stage uploads the binaries to a versioned path which they later consume during their tests.

Upload nodeadm induvidually during test stage

---

go.mod
go.sum
hybrid-nodes-cdk/lib/nodeadm/policies.ts
test/e2e/cluster/create.go

The default for eks cloudwatch groups the retention is set to Infinite.  This adds a tag to the group (so we can eventually add deleting groups) and changes the retention to 14 days.

tags and sets retention policy on eks cluster cw log groups

---

test/e2e/constants/constants.go
test/e2e/nodeadm/commands.go
test/e2e/run/e2e.go
test/e2e/run/report.go
test/e2e/suite/test_node.go

This adds the nodeadm version as a report entry and e2e-result field so we can easily see the version of nodeadm used by the e2e test.

adds nodeadm version as e2e test report entry

---

test/e2e/cleanup/sweeper.go
test/e2e/cleanup/vpc.go

This PR adds functionality to clean up tgw in sweeper. If somehow cfn fails to clean up transit gateway after #363 is merged, it can be cleaned up in sweeper.

Clean up transit gateways in sweeper

---

test/e2e/os/testdata/nodeadm-init.sh

We have seen failures where the install will hang and the test will timeout and the resulting logs are a bit confusing to follow, they look like the node just died.  This doesn't fix anything, but it will make it more clear when there the install process takes more than 8 mins that something in that process was the issue and not a node dying.

adds --timeout to nodeadm install in e2e tests

---

test/e2e/run/e2e.go
test/e2e/run/output.go

In the canary we would like to add additional data to the printed json blob.  This should allow us to use a different struct, wrapping the E2EResult, and then pass that to the PrintJSON func.

allows printJson to take any for printing e2eresult

---

test/e2e/cfn/cloudformation.go
test/e2e/cleanup/cloudformation.go
test/e2e/cluster/stack.go
test/e2e/credentials/stack.go

We had a failure during the beforesuite, due to the role name conflicting, but we werent including the failure reason for the cred stack. We were already doing this for the infra stack.
This moves the code around a bit to reuse the same waitFor/failurereason logic in both the cred and infra stack as well as the stack cleanup.

include cred stack failure reason in error

---

cmd/e2e-test/node/create.go
cmd/e2e-test/ssh/ssh.go

Small improvements to create node to allow for instance size. Fixes ssh to find the running instance in case you reuse the instance name and have deleted instances.

adds instance size to create node and fix ssh

---

test/e2e/addon/podidentityverify.go

Bump timeout to 10 mins for pod identity add on since we're seeing lots of context exceeded errors due to 2 minute timeout; from logs it has looked like it's taken up to 7 mins to add on to be ready (often due to waiting on a single pod in daemonset to be in ready state)

Bump pod identity timeout to 10 mins

---

hybrid-nodes-cdk/lib/constants.ts
test/e2e/kubernetes/version.go

Removes k8s 1.25 from e2e tests as its no longer in extended EKS support.
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

Remove k8s 1.25 from e2e tests

---

cmd/e2e-test/node/create.go
test/e2e/peered/node.go

We can't use the `node create` to create ec2 instance with different instance types. This is inconvenient when I need to create EC2 GPU instance.
With this PR, now we can pass instance type to `node create` command. Sample command:
```
./_bin/e2e-test node create -c ssm -f e2e-param.yaml -o al23 -a amd64 -t g4dn.xlarge al23-2
```
Tested manually

Add instance type param to node create command

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/cluster/create.go
test/e2e/cluster/stack.go

While testing metrics server, I found the availability for metrics server endpoint bounce between true and false. It turns out that when it fails, the network traffic is routed to private subnet of hybrid VPC eventually, which doesn't have pod CIDR route.
In this PR, I am removing private subnet from hybrid VPC for now. Current setup for E2E doesn't require private subnet at this point. 
Tested manually.

Remove private subnet from hybrid VPC for e2e

---

hack/SKIPPED_TESTS.yaml

We currently do not run any ubuntu-docker repo test, this enables simple flow docker tests on ubuntu 2404
```
With OS ubuntu2404-amd64-docker and with Credential Provider iam-ra [ubuntu2404-amd64-docker, iam-ra, simpleflow, init]
```

Enable one ubuntu docker test

---

test/e2e/credentials/cfn-templates/hybrid-cfn.yaml

Description of changes:
IAM role name collisions were occurring between stacks when their UUIDs started with the same segment. Modified the IAM role naming pattern to use the full UUID instead of first segment

Update IAM role names to be unique to avoid collisions

---

cmd/nodeadm/install/install.go
cmd/nodeadm/uninstall/uninstall.go
cmd/nodeadm/upgrade/upgrade.go
internal/containerd/install.go
internal/flows/install.go
internal/flows/uninstall.go
internal/flows/upgrade.go
internal/packagemanager/packagemanager.go
internal/tracker/artifacts.go
test/integration/cases/install-containerd-source-none/expected-nodeadm-tracker
test/integration/cases/uninstall-with-source-none/config.yaml
test/integration/cases/uninstall-with-source-none/expected-nodeadm-tracker
test/integration/cases/uninstall-with-source-none/run.sh
test/integration/cases/upgrade-with-source-none/config.yaml
test/integration/cases/upgrade-with-source-none/expected-nodeadm-tracker
test/integration/cases/upgrade-with-source-none/mock-containerd.sh
test/integration/cases/upgrade-with-source-none/run.sh
test/integration/helpers.sh
test/integration/infra/Dockerfile

see #534 for background
Fixes handling of containerd-source:none during upgrade and install.  Previously during upgrade nodeadm was yum/apt updating and during uninstall it would have removed containerd even if the user had ran install with source:none.
This PR is broken into 3 commits:
- the first commit adds an integration test to prove the failure, replicating the error on al23 requires a bit of yum magic since containerd is provided in the yum repo, whereas on rhel yum gets confused easier since there is no containerd package in the default repos
- the second commit is the bare minimum fix for this issue where because we were not properly handling the empty value of the Containerd "enum" in the tracker struct/file, we were comparing …

fixes upgrade and uninstall when using containerd-source:none

---

test/e2e/os/rhel.go
test/e2e/os/testdata/rhel/9/cloud-init.txt
test/e2e/os/testdata/ubuntu/2404/cloud-init.txt
test/e2e/os/ubuntu.go
test/e2e/suite/peered_vpc.go

This adds a new rhel9-amd64-no-source and ubuntu2404-amd64-no-source test to validate the upgrade/uninstall flow when using containerd-source:none.  The integration test already covers al23 and I dont think this test is need across all OS/Versions since the behavior is similar enough between them.

adds e2e test to validate containerd-source none

---

hack/validate-release.sh

Adds a regex to filter out the version when comparing versions. Fixes error where we saw `Version mismatch! Released version (Version: v1.0.5) does not match expected version (v1.0.5)`

Add regex to filter version output for comparison in validate-release.sh

---

internal/artifact/install.go
internal/artifact/install_test.go

Use golang std gzip/tar libs to extract the cni plugins tgz instead of exec-ing to tar.

implements untar/gz in go intead of exec-ing out

---

internal/artifact/source.go
internal/artifact/source_test.go
internal/aws/manifest.go
internal/aws/source.go

We are going to start publish .gz files for the individual binaries we download via nodeadm install.  This adds support for these in the manifest, which does not currently exist today, but will after the next platform release.  Currently during install we download ~200MB from the cloudfront distro, once these are all available as gz versions this will drop down to ~50MB.

adds support for gzipped uri in artifacts manifest

---

go.mod
go.sum
hybrid-nodes-cdk/lib/nodeadm/policies.ts
test/e2e/cleanup/cloudwatchlogs.go
test/e2e/cleanup/resource_tagging.go
test/e2e/cleanup/sweeper.go

During e2e test setup we enable eks cluster logs to cloudwatch.  We set the retention period to 14 days.  This PR adds cleanup to remove the log groups after 15 days, to keep from filling up the account with old/empty log groups.

adds cloudwatch log group cleanup for e2e clusters

---

buildspecs/build-nodeadm.yml
buildspecs/dev-release-nodeadm.yml
buildspecs/test-nodeadm.yml
hack/release-nodeadm.sh
test/e2e/os/testdata/nodeadm-init.sh
test/e2e/os/testdata/nodeadm-wrapper.sh

This adds a gz "build" of the nodeadm bins during the build/test/release process so our customers (and canaries) can download the gz version (~90MB vs 20MB).
When uploading the .gz version to s3, we explicitly add the content-encoding override.  This allows for curl to be able to automatically decompress for us during download and avoiding needing to add an additional url config to the test resource config.  the `--compress` flag on curl will only decompress if the url returns with the proper content-encoding, if it does not, itll just write it out as is.  This allows for us to make this change without worrying about breaking existing usage/canaries where we config the nodeadm url to be a non-gzip version.
Also change the cloud-init …

adds gz build of nodeadm through release process/e2e

---

internal/kubernetes/retry.go
internal/kubernetes/retry_test.go
internal/kubernetes/wait.go
internal/kubernetes/wait_test.go
internal/retry/maxerrors.go
internal/retry/maxerrors_test.go
internal/retry/network.go
internal/retry/network_test.go
internal/retry/retry.go
internal/retry/retry_test.go

This introduces a generic retrier. I don't expect us to use this retrier directly most of the time, it's just a building block to construct higher level retry helpers, depending on the usecase.
I wrote a few of these higher level retry helpers, like a few for Kubernetes API operations (`Get` and `List` and "wait for condition") and one for general network requests. They are all backed by the generic retrier.

Add helpers for most common retry usecases

---

buildspecs/cleanup-nodeadm.yml

This should not affect CI since we only create clusters with this prefix in CI, but I occasionally create canary clusters in my account which use a different cluster prefix.  This ends up triggering a failure in my devstack runs because our cdk limits the role for cleanup to only clusters with the `nodeadm-e2e-tests` prefix.  This will ensure it wont even look at the canary clusters.

limit e2e tests sweeper to nodeadm-e2e-tests clusters

---

.gitignore
Makefile
internal/kubernetes/wait.go
test/e2e/addon/addon.go
test/e2e/addon/nodemonitoringagent.go
test/e2e/addon/podidentityverify.go
test/e2e/kubernetes/pod.go
test/e2e/suite/addon_ec2.go
test/e2e/suite/addons/addons_test.go

This PR adds end-to-end tests for the EKS Node Monitoring Agent addon. Key changes include:
**Added**
- New smoke test suite for addons testing
- Node Monitoring Agent E2E test implementation
- Support for validating node conditions and events created by monitoring agent
- Log collection capabilities to addon struct for debugging failures
Tested with k8s 1.31 and Cilium

node monitoring agent test

---

internal/containerd/daemon.go
internal/daemon/interface.go
internal/flows/init.go
internal/iamrolesanywhere/daemon.go
internal/kubelet/daemon.go
internal/node/hybrid/aws.go
internal/ssm/config.go
internal/ssm/daemon.go

Adding retries with backoff for SSM agent registration to handle network connectivity issues (connection reset errors). Uses cmd.Retry with a 10seconds backoff and 60seconds timeout allowing 6 retry attempts before failure

Add retries for ssm agent registration

---

internal/aws/sts/validate.go
internal/aws/sts/validate_test.go
internal/iamrolesanywhere/validate.go
internal/iamrolesanywhere/validate_test.go
internal/kubernetes/access_test.go
internal/kubernetes/connection.go
internal/kubernetes/connection_test.go
internal/kubernetes/unauthenticated.go
internal/kubernetes/unauthenticated_test.go
internal/node/pods.go
internal/node/pods_test.go
internal/node/validate.go
internal/node/validations.go
internal/node/validations_wb_test.go
internal/ssm/validate.go
internal/ssm/validate_test.go

Seeing issues in the e2e tests where the validations in the debug command fails due to timeouts. Wrapping these operations to retry to fix the flakiness

Add retries around kubernetes validations

---

test/e2e/peered/cluster.go

We see the following tgw issue occasionally.
```
Expected should build peered VPC test config
Unexpected error:
<*fmt.wrapError | 0xc0009aca60>: 
getting peered VPC for the given cluster nodeadm-canary-1-30-vuDGmFQ8J6-1747907576: expected 2 TGW attachments for TGW tgw-0a5b45657366b7cd6, got 3
{
msg: "getting peered VPC for the given cluster nodeadm-canary-1-30-vuDGmFQ8J6-1747907576: expected 2 TGW attachments for TGW tgw-0a5b45657366b7cd6, got 3",
err: <*errors.errorString | 0xc0009af9a0>{
s: "expected 2 TGW attachments for TGW tgw-0a5b45657366b7cd6, got 3",
},
}
occurred
```
Similar to #552 , we now only retrieve tgw attachments that are in available state for given tgw.
*Documentation added/planned (if …

Only retrieve tgw attachments that are in available state for given tgw

---

buildspecs/test-nodeadm.yml
test/e2e/suite/nodeadm/nodeadm_test.go

Currently we run across all kube versions/cni combos concurrently in CI.  We see issues due to this from time to time because the test end up hitting points across the various builders around the same time, which can trigger large amount of concurrent api requests.
This adds a random wait between 0-30 seconds before starting each test to try and give a bit more variance.

adds random sleep prior to kicking off ci run

---

test/e2e/os/arch.go
test/e2e/os/testdata/install-containerd.sh
test/e2e/os/testdata/rhel/9/cloud-init.txt
test/e2e/os/testdata/ubuntu/2404/cloud-init.txt
test/e2e/os/ubuntu.go

I would occasionally get an rpm.lock error when running the source-none, which were using cloud-init to install containerd, in my devstack.
This introduces a basic script which attempts to wait for existing yum/apt operations and then also retries up to 5 times on failure to help ensure containerd is installed before we run `nodeadm install` for the containerd-source:none tests.

improves containerd install for the source-none tests

---

internal/kubernetes/retry.go
internal/kubernetes/retry_test.go
internal/kubernetes/wait.go
internal/kubernetes/wait_test.go
test/e2e/addon/addon.go
test/e2e/kubernetes/daemonset.go
test/e2e/kubernetes/namespace.go
test/e2e/kubernetes/node.go
test/e2e/kubernetes/pod.go
test/e2e/kubernetes/serviceaccount.go

Switch most of the kubernetes retries in e2e to use the new helpers.  Most changes are pretty straightforward.  
For a couple, like WaitForNode and WaitForPod variants, I used the ListAndWait with a listOption filter vs using GetAndWait which does not give the error we would need to check if it was NotFound.
There are a few remaining uses of retry.OnError I have left for a future PR (if at all).  These are mostly cases that may be longer running actions, such as drain or getPodLogs.

updates pod/node retries in e2e

---

test/e2e/ec2/instance.go

We've seen a couple times of the route failing to delete due to missing. This missing is almost expected based on how the code is written where the route cleanup is called multiple times.  Route deletion appears to be eventually consistent, like most ec2 resources, and we usually get lucky in the sense that the second delete either happens long enough after where the describeroutetables call returns nothing or describeroutetables returns the route and by the time we try to delete it its still available and the second delete is allowed with no error.
In the case that it failed, it was returned via the describeroutetables and deleted before we triggered the delete call.
I tested this by running the delete in a loop with sleeps and confirmed …

handles route not found during cleanup

---

Makefile
internal/packagemanager/packagemanager.go

* Disable CGO for nodeadm build target. Without this, the `make build` target throws a linker error:
```
/opt/homebrew/bin/go build -ldflags "-X github.com/aws/eks-hybrid/cmd/nodeadm/version.GitVersion=0.0.0 -X github.com/aws/eks-hybrid/internal/aws.manifestUrl=https://hybrid-assets.eks.amazonaws.com/manifest.yaml -s -w -buildid='' -extldflags -static" -trimpath -o /Users/arnchlm/eks-hybrid/_bin/nodeadm cmd/nodeadm/main.go
/opt/homebrew/Cellar/go/1.24.3/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
/usr/bin/cc -arch arm64 -Wl,-S -Wl,-x -o $WORK/b001/exe/a.out -Qunused-arguments /var/folders/sv/cpy5yzy57mj8xj8q35l9l_8h0000gq/T/go-link-518237138/go.o /var/folders/sv/cpy5yzy57mj8xj8q35l9l_8h0000gq/T/go-link-518237138/000000.o …
```

Disable CGO for nodeadm build target

---

buildspecs/build-nodeadm.yml
buildspecs/dev-release-nodeadm.yml
buildspecs/prod-release-nodeadm.yml
hack/build-nodeadm.sh
hack/release-nodeadm.sh
hack/upload-dev-release-artifacts.sh
hack/validate-release-artifacts.sh
hack/validate-release.sh
scripts/make_attribution.sh

This reworks the build and release scripts to better support testing throughout the process. As much as can be as been pushed to the build + staging build nows.  The prod release is a pretty simple s3 sync and then validation.
Added a validation script to ensure we are publishing the expected artifacts throughout the various points in the process.
Fixed the checksum generation to remove the `_bin/linux` path in the final files, which makes validating for the user complicated. The new format will be 
`e2e18a56947384781ae61b9d58d57d9ddf0fe9dad1cbfe0e0323c7ea497d93aa  nodeadm.gz`
By submitting this pull request, I confirm that you can use, modify, copy, and …

rework release/build scripts to limit prod release work

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/cluster/stack.go
test/e2e/securitygroup/ingress.go

This PR refactors the E2E test CloudFormation template generation to generate and inject security group ingress rules required by various EKS addons.
- **Renamed** `test/e2e/cluster/cfn-templates/setup-cfn.yaml` → `setup-cfn.yaml.template`
- **Added** template placeholder `{{.AddonSecurityGroupIngress}}` for dynamic content injection
Created `test/e2e/securitygroup/` package with:
- Defines `IngessConfig` struct for security group configuration
- Provides `DefaultIngress()` function with predefined addon service ports
- `GenerateSecurityGroupIngressCFN()`: Creates CloudFormation YAML for security group ingress resources
- `GenerateSetupCFNWithIngress()`: Injects generated ingress rules into the main CloudFormation template
- **Modified** …

security group ingress cluster setup template

---

hybrid-nodes-cdk/lib/nodeadm/policies.ts

We need permissions to create and execute changesets in order to use cloudformation's LanguagesExtensions. 

update permissions to use cloudformation LanguagesExtension

---

internal/iamrolesanywhere/aws_config.go
internal/iamrolesanywhere/aws_signing_helper_update_service.tpl
internal/iamrolesanywhere/daemon.go
internal/iamrolesanywhere/daemon_test.go
internal/iamrolesanywhere/testdata/expected-systemd-service-unit-with-proxy

We previously fixed the iam-ra generated aws config to pass the --with-proxy flag when appropriate, but missed the update service.  This applies similiar logic to the service generation to ensure the --with-proxy flag is passed to the aws_signing_helper cmd.
Note, I will update the [docs](https://docs.aws.amazon.com/eks/latest/userguide/hybrid-nodes-proxy.html) page to include the need to add a similar service env file for the iam-ra update service.  As a future improvement, this service file along with most of the others listed on that docs page *could* be created by nodeadm.
By submitting this pull request, I confirm that you can use, modify, copy, and …

fixes iam-ra update service when used with proxies

---

internal/packagemanager/packagemanager.go

When downloading the gpg key, this change uses the existing helper for downloading files with retries.

changes gpgkey http get to use existing retryable http

---

hybrid-nodes-cdk/lib/nodeadm/policies.ts

Got the following error message for the latest deployment in nodes build pipeline.
```
This AWS::IAM::Policy resource is in a UPDATE_FAILED state.
Resource handler returned message: "Maximum policy size of 10240 bytes exceeded for role nodeadm-build-65465437107-nodeadme2etestsprojectRol-S8mdpYtKocHA (Service: Iam, Status Code: 409, Request ID: 9dd12436-e073-428c-9a9b-3440af1e163a) (SDK Attempt Count: 1)" (RequestToken: 89246591-4d80-2d15-b790-ae68b8a3184e, HandlerErrorCode: ServiceLimitExceeded
```
Consolidate policies to reduce size of role for now. Policy should still remain the same after this change. 
By submitting this pull request, I confirm that you can use, …

Consolidate policies to reduce size of role

---

hack/upload-dev-release-artifacts.sh
hack/validate-release-artifacts.sh

Fix staging and prod artifact paths to include the `bin` folder.

Fix staging and prod artifact paths

---

test/e2e/cleanup/eks.go
test/e2e/cleanup/vpc.go
test/e2e/credentials/ssm.go
test/e2e/credentials/stack.go
test/e2e/ec2/instance.go

We are hitting a validation error during SSM activation creation, when the IAM role is not ready yet so the client assumes we're associating a non-existent role with the activation.
```console
expected to build nodeconfig: failed to create SSM activation for node simpleflow-node-ssm-al23-amd64: creating SSM activation: operation error SSM: CreateActivation, https response error StatusCode: 400, RequestID: 608d0ae8-bc93-4480-9a30-95afdfc16656, api error ValidationException: Nonexistent role or missing ssm service principal in trust policy: arn:aws:iam::<account>:role/NodeadmE2E/<ssm role name/session>
```
This PR adds this exception type as a retryable error to work around the intermittent unavailability of the IAM role right after its creation.
Also I've changed the E2E code to use the …

Retry SSM activation creation on IAM role validation failures

---

test/e2e/cluster/stack.go

Increase timeouts on waiting stacks to be created from 7 minutes to 9 minutes. The context behind this is that there is a 5 minute timeout on the jumpbox resource signal. However, the stack first creates a role/instance profile and cfn has a hardcoded 2 (or 2.5) mins wait before assuming the instance profile is ready.
So we need to wait a bit longer than 7 minutes to ensure the tests can retry creating the instance if the signal handler times out.

increase cfn stack timeout

---

test/e2e/cleanup/eks.go

At least one test run timed out waiting for cluster to delete. Looking at cloudtrail events, there was another event for that cluster 16 minutes after it received the DeleteCluster event. That event failed since the cluster did not exist, which suggests the cluster took somewhere between 15 and 16 minutes to delete. 

increase cluster transition wait times

---

cmd/e2e-test/node/create.go
test/e2e/peered/node.go
test/e2e/suite/test_node.go

Some tests failed waiting for EC2 instance for node to be running. We expect it to retry if an ec2 never goes to running state as well as collecting logs from the ec2 on failure. However, neither of these things were happening. 
Move wait for ec2 outside of NodeCreate.Create. We already do this step in `n.waitForNodeToJoin(ctx, flakeRun)` which is the intended place for wait. If we keep it inside NodeCreate.Create(), then it never reaches DeferCleanup() which contains the logic for collecting logs and is only called after NodeCreate.Create.
Also added wait for ec2 in `cmd/e2e-test/node/create.go`.
By submitting this pull request, I confirm that you can use, modify, …

fix e2e retry and cleanup on create node

---

test/e2e/cluster/create.go
test/e2e/cluster/stack.go

Validate that all necessary output from DescribeStack is non-empty to avoid create cluster calls like `"requestParameters": {
"resourcesVpcConfig": {
"securityGroupIds": [
""
],
"subnetIds": [
"",
""
]
},
"clientRequestToken": "***",
"roleArn": "",
"name": "***",
"accessConfig": {
"authenticationMode": "API_AND_CONFIG_MAP"
},`
`
Phase: SetupTestInfrastructure Failure: creating E2E test infrastructure: creating 1.33 EKS cluster: creating EKS hybrid cluster: operation error EKS: CreateCluster, https response error StatusCode: 403, RequestID: ...... , api error AccessDeniedException: Cross-account pass role is not allowed. Status: failure`
By submitting this pull …

Check resourcesStackOutput params are nonempty after creating stack

---

test/e2e/addon/podidentityverify.go

We are seeing s3 commands with the aws cli fail due to rate limits from additional tests. Setting the AWS_MAX_ATTEMPTS env var on the awscli pod and configuring it to 10 to add retries to mitigate the issue.

Add AWS_MAX_ATTEMPTS env var to awscli pod

---

internal/kubernetes/cert.go
internal/node/hybrid/certificate_validator.go
internal/node/hybrid/certificate_validator_test.go
internal/node/hybrid/hybrid.go
internal/node/hybrid/validator.go

Code Refactor - replace enum-based errors with specific error types for certificate validation
- Convert ValidationError with enum types to individual error structs for better error handle
*Testing (if applicable):* yes
- Run unit test and integration test
- Test on hybrid node 
**Kubelet certificate validation**
root@hybrid-node:/home/eksahybrid# ./nodeadm debug -c file://nodeConfig.yaml
```
* Validating access to AWS SSM API endpoint [Success]
* Validating authentication against AWS [Success]
* Validating access to Kubernetes API endpoint [Success]
* Validating unauthenticated request to Kubernetes API endpoint [Success]
* Validating authenticated request to Kubernetes API endpoint [Success]
* Validating Kubernetes identity matches a …
```

Refactor: replace enum type for better type safety

---

cmd/nodeadm/debug/debug.go
cmd/nodeadm/init/init.go
internal/node/hybrid/hybrid.go
internal/node/hybrid/ntp_test.go
internal/system/ntp.go
internal/system/ntp_test.go
internal/system/swap_validator.go

Add in-flight validation for NTP sync for init command, and separate validation fot debug command. 

Add validation for NTP sync

---

test/e2e/suite/nodeadm/nodeadm_test.go
test/e2e/suite/peered_vpc.go

Simplify Bottlerocket OS list in E2E tests by hardcoding it instead of doing a double for-loop.

Simplify Bottlerocket OS list in E2E tests

---

test/e2e/suite/nodeadm/nodeadm_test.go
test/e2e/suite/peered_vpc.go

Fix nil pointer in BR OS provider list, due to not setting clients.

Fix nil pointer in BR OS provider list

---

internal/aws/ecr/ecr.go
internal/aws/ecr/ecr_test.go
internal/aws/source.go
internal/configenricher/interface.go
internal/flows/init.go
internal/flows/upgrade.go
internal/node/ec2/configenricher.go
internal/node/hybrid/configenricher.go
internal/node/hybrid/configenricher_test.go

Removed hardcoded ecr region to account mappings for regions where hybrid nodes is supported.
Restructured the logic to use the ecr region account mapping from the manifest instead.

Use manifest to determine ECR

---

test/e2e/cluster/stack.go

We occasionally got
`Phase: SetupTestInfrastructure Failure: creating E2E test infrastructure: creating stack for cluster infra: setting up jumpbox: jumpbox getting private key from ssm Status: failure`.
I suspect whats happening is that the role's credentials were not generated and available via IMDS for the jumpbox yet at the time the test tried to run the aws ssm get-parameter call on the jumpbox (via the SSM Agent, which is unrelated to our problem but was slightly confusing since they're both ssm). I think a few retries will fix the issue since it will give more time for the role creds to become available in IMDS.
Ran E2E test suite to verify retries did not affect functionality.
*Documentation …

Fix IAM credential propagation race condition in jumpbox private key download

---

cmd/e2e-test/node/create.go
test/e2e/addon/nvidiadeviceplugin.go
test/e2e/addon/testdata/gpu-pod.yaml
test/e2e/addon/testdata/nvidia-device-plugin-v0.17.1.yaml
test/e2e/kubernetes/pod.go
test/e2e/peered/network.go
test/e2e/peered/types/types.go
test/e2e/suite/addons/addons_test.go
test/e2e/suite/peered_vpc.go

Validate Nvidia device plugin functionality. It requires PR #587 
In this PR, I add the following to nvidia device plugin:
- Create `nvidia` runtime class
- Create Nvidia device plugin v0.17.1
- Create test pod `gpu-pod`
- Validate the test pod succeed
- Move `K8S` type from `peered` to `peered/types` to avoid circular dependency issue.

Validate nvidia device plugin functionality in e2e tests

---

hybrid-nodes-cdk/lib/constants.ts

Remove K8s 1.27 from K8s versions

Remove K8s 1.27

---

cmd/nodeadm/debug/debug.go
internal/system/ntp.go
internal/system/swap_validator.go
internal/system/ulimit.go
internal/system/ulimit_validator.go
internal/system/ulimit_validator_test.go

Add node ulimit validations to `nodeadm debug` command.
```console
$ /tmp/nodeadm debug -c file:///nodeadm-config.yaml
* Validating access to AWS SSM API endpoint [Success]
* Checking NTP synchronization status [Success]
* Checking swap configuration {"level":"info","ts":"2025-07-24T03:00:19.773Z","caller":"system/swap_validator.go:86","msg":"No swap detected"}
[Success]
* Checking ulimit configuration [Success]
* Validating authentication against AWS [Success]
* Validating access to Kubernetes API endpoint [Success]
* Validating unauthenticated request to Kubernetes API endpoint [Success]
* Validating authenticated request to Kubernetes API endpoint [Success]
* Validating Kubernetes identity matches a Node identity [Success]
* Validating access to Kube-API server through VPC IPs …
```

Add validation for node ulimits

---

Makefile
hack/e2e-cleanup.sh
test/e2e/cleanup/managed_nodegroups.go
test/e2e/cleanup/sweeper.go
test/e2e/credentials/cfn-templates/hybrid-cfn.yaml
test/e2e/credentials/stack.go
test/e2e/kubernetes/deployment.go
test/e2e/kubernetes/node.go
test/e2e/kubernetes/pod.go
test/e2e/kubernetes/service.go
test/e2e/peered/cluster.go
test/e2e/suite/addon_ec2.go
test/e2e/suite/mixed_mode/mixed_mode_test.go
test/e2e/suite/peered_vpc.go
test/integration/cases/containerd-config/run.sh
test/integration/cases/image-credential-provider/run.sh
test/integration/cases/kubelet-config-new-instance-type/expected-kubelet-config.json
test/integration/cases/kubelet-config-new-instance-type/run.sh
test/integration/cases/kubelet-config-set-empty/expected-kubelet-config.json
test/integration/cases/kubelet-config-set-empty/run.sh
test/integration/cases/kubelet-config/expected-kubelet-config.json
test/integration/cases/kubelet-config/run.sh
test/integration/cases/kubelet-flags/run.sh
test/integration/cases/kubelet-version/run.sh

Adding end-to-end testing for mixed mode EKS clusters where hybrid nodes and cloud-managed nodes coexist. 
Test Coverage :
- Cross-VPC pod-to-pod communication (both directions)
- Cross-VPC service discovery with DNS resolution across node types (both directions)
- CoreDNS optimization for mixed mode

Adding Mixed-Mode tests to e2e

---

hack/run-e2e.sh

Makes the parallel ginkgo processes number a variable in run-e2e.sh for clarity

Make parallel test executions a variable in run-e2e.sh

---

cmd/nodeadm/init/init.go
internal/node/hybrid/hybrid.go
internal/node/hybrid/nodeinactive_validator.go
internal/node/hybrid/nodeinactive_validator_test.go
internal/node/hybrid/versionskew_validator_test.go
internal/validation/error.go
internal/validation/logger_printer.go
internal/validation/runner.go

*Issue:*
https://github.com/aws/eks-anywhere-internal/issues/3380
These changes adds a validation that checks if node was cleaned up properly and not potentially joined to another cluster when doing `nodeadm init`.
*Testing:*
```bash
{"level":"info","ts":"2025-08-01T01:08:17.562Z","caller":"hybrid/hybrid.go:162","msg":"Validating proxy configuration..."}
{"level":"info","ts":"2025-08-01T01:08:17.562Z","caller":"hybrid/hybrid.go:170","msg":"Validating node is inactive..."}
{"level":"warn","ts":"2025-08-01T01:08:17.562Z","caller":"hybrid/hybrid.go:172","msg":"Validation failed","error":"kubelet args environment file /etc/eks/kubelet/environment exists","remediation":"Ensure the hybrid node is made inactive by running 'nodeadm uninstall' before attaching to the EKS …
```

Adding validation to ensure node cleanup and inactive

---

Makefile

Change `make fmt` to use gofumpt instead of go fmt to pass our linter.

Update make fmt to use gofumpt instead of go fmt

---

test/e2e/cni/testdata/cilium/mirror-cilium.sh

Update mirror-cilium script to use public ecr rather than quay.io when inspecting cilium images

update mirror-cilium.sh to point to public ecr

---

test/e2e/addon/pcaissuer.go

We are seeing the following in our E2E tests.
```
[FAILED] should support cert-manager webhook functionality in mixed mode
Expected cert-manager should validate certificates in mixed mode
Unexpected error:
<*fmt.wrapError | 0xc000a60940>: 
AWS PCA Issuer validation failed: failed to setup AWS Private CA: waiting for CA creation: unexpected CA status: ACTIVE
{
msg: "AWS PCA Issuer validation failed: failed to setup AWS Private CA: waiting for CA creation: unexpected CA status: ACTIVE",
err: <*errors.errorString | 0xc0008dbad0>{
s: "failed to setup AWS Private CA: waiting for CA creation: unexpected CA status: ACTIVE",
},
}
occurred
In [It] at: /codebuild/output/src740480428/src/test/e2e/suite/mixed_mode/mixed_mode_test.go:390 @ 2025-08-11 22:31:23
```
Ideally a new certificate authority …

Set idempotency token in CreateCertificateAuthority to differentiate calls between tests

---

test/e2e/suite/addons/addons_test.go

We are seeing the following issue in our add-on test pipeline.
```
[FAILED] runs kube state metrics tests on Bottlerocket
Expected kube state metrics should have created successfully
Expected success, but got an error:
<*errors.errorString | 0xc0009c7e60>: 
failed to wait for kube state metrics replicas: deployment kube-state-metrics replicas never became ready: max attempts 3 reached: deployments.apps "kube-state-metrics" not found
{
s: "failed to wait for kube state metrics replicas: deployment kube-state-metrics replicas never became ready: max attempts 3 reached: deployments.apps \"kube-state-metrics\" not found",
}
In [It] at: /codebuild/output/src1933621483/src/test/e2e/suite/addons/addons_test.go:365 @ 2025-07-25 20:31:18
```
We have seen the same issue for other add-ons as well, …

Reorganize add-on tests to fix concurrency issue between regular OS and Bottlerocket

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml

*Issue:*
The EKS Hybrid test infrastructure was experiencing intermittent failures during CloudFormation stack deletion with the error:
```
Network has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
```
This occurred because EC2 Fleet instances with public IP addresses were preventing the Internet Gateway from being detached during stack deletion.
Basically, CloudFormation attempted to detach the Internet Gateway before terminating the Fleet instances
Added missing dependencies to ensure proper creation and deletion order.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

add dependencies on jumpbox fleet

---

cmd/e2e-test/ssh/ssh.go
internal/api/status.go
internal/util/ec2_test.go
test/e2e/peered/keypair.go

`aws-sdk-go` is deprecated
update `aws-sdk-go/aws` to `aws-sdk-go-v2/aws`.
Tested under personal dev stack.

Upgrade aws-sdk-go/aws to aws-sdk-go-v2/aws

---

.github/workflows/build-and-test.yml
.github/workflows/build-e2e-test-binaries.yml
.github/workflows/golangci-lint.yml
.github/workflows/integration-test.yml
ATTRIBUTION.txt
Makefile
go.mod
test/integration/infra/Dockerfile

Upgrading to Go 1.25 everywhere.

Upgrade to Go 1.25

---

test/e2e/addon/addon.go

We are unable to choose which add-on versions to use during E2E tests. It's okay in most cases. However for S3 mountpoint CSI driver add-on, the default install version is v1. For the testing we want to install v2 version.
Add Version field to Addon so we can set it if needed for E2E test
Manually tested

Add Version field to Addon so we can set it if needed for E2E test

---

test/e2e/kubernetes/service.go
test/e2e/suite/mixed_mode/mixed_mode_test.go

Add retries to fix network issues in service connectivity tests

Add retries to fix network issues in service connectivity tests

---

internal/ssm/install.go
internal/ssm/install_test.go
test/integration/cases/install-with-ssm/expected-ssm-agent-config.json
test/integration/cases/install-with-ssm/run.sh

*Issue #, if available:* N/A
Reduces SSM agent credential retry backoff from 1800 seconds  to 60 seconds. Fixes delay in credential rotation caused by excessive backoff time when SSM agent cannot reach endpoints.
```javascript
When network disconnections occur due to networking issues and the SSM agent cannot reach
SSM endpoints, it enters an exponential backoff retry mechanism with a maximum delay of up to
30 minutes between retry attempts. After network connectivity is restored, the SSM agent can
still be in the backoff state and won't attempt to refresh expired credentials for up to 30 minutes,
leaving the nodes unable to authenticate with the EKS control plane during this period.
This change improve the responsiveness of credential rotation failure during …
```

Reduce SSM credential retry backoff interval to 60 seconds

---

test/e2e/kubernetes/daemonset.go
test/e2e/kubernetes/deployment.go

We can't test add-on in our E2E if the anti-affinity rule for add-on is not updated for hybrid nodes
For new add-on that are not updated to be compatible with hybrid nodes yet, we can remove the anti-affinity rule in our E2E tests to allow the add-on to be provisioned on hybrid nodes.
Tested manually

Add functions to remove nodeAffinity rules from deployment and daemonset for E2E

---

cmd/e2e-test/cleanup/cleanup.go
cmd/e2e-test/node/create.go
cmd/e2e-test/rune2e/command.go
cmd/e2e-test/setup/setup.go
cmd/e2e-test/ssh/ssh.go
cmd/e2e-test/sweeper/sweeper.go
test/e2e/os/bottlerocket.go
test/e2e/suite/peered_vpc.go

This PR enhances the reliability of E2E tests by adding consistent retry configuration to all AWS client initializations across test commands. The change addresses potential transient failures in AWS API calls during test execution.
```
config.WithRetryer(func() aws.Retryer {
return retry.AddWithMaxBackoffDelay(
retry.AddWithMaxAttempts(
retry.NewStandard(),
10, // Max 10 attempts
),
10*time.Second, // Max backoff delay
)
}),
```
__Retry Policy:__
- __Max Attempts:__ 10
- __Max Backoff Delay:__ 10 seconds
- __Strategy:__ Exponential backoff with jitter
- __Total Max Wait Time:__ ~67 seconds

Add retryer to AWS configs in tests

---

test/e2e/cluster/cfn-templates/setup-cfn.yaml

The jumpbox instance will fail create if it falls back to a1 instance type in a region where a1 isn't supported
`Your requested instance type (a1.medium) is not supported in your requested Availability Zone (eu-west-3a)`
This PR removes a1 instance type with the more widely available t4g instance types for better availability.

Fix E2E jumpbox instance availability issues

---

.gitignore
test/e2e/credentials/stack.go

Tests sometimes failing with missing CFN stack outputs
```
Creating access entry	{"ssmRoleArn": ""}
operation error EKS: CreateAccessEntry, exceeded maximum number of attempts, 40, https response error StatusCode: 400, RequestID: 73a71407-0e38-43f2-b7d2-4947857ba3a6, InvalidParameterException: The principalArn parameter is required.
```
This PR adds retries to ensure all the stack outputs are available and non-empty before consuming them.

Ensure stack outputs are non-empty in e2e tests

---

test/e2e/addon/externaldns.go
test/e2e/addon/testdata/nginx-external-dns.yaml
test/e2e/suite/addons/addons_test.go

No smoke tests for external-dns addon
There will be a series of PRs to add smoke test for external-dns addon. This is the fifth part, which includes the following:
- Update add-on configuration to have domain filter and policy
- Find hosted zone id and name based on cluster name we set in tags 
- Replace hosted zone name in test service yaml 
- Deploy test service yaml
- Wait for the test service to be ready
- Validate the dns in test service are synced to route 53 hosted zone
- Delete test service
- Validate the dns in test service are deleted when the test service is deleted
First part: #725 
Second part: #730 
Third part: #738 
Fourth part: #739 
Tested manually and also tested with my dev stack
By submitting …

Validate dns are synced to hosted zone for external-dns smoke test

---

test/e2e/addon/addon.go
test/e2e/addon/externaldns.go
test/e2e/addon/pcaissuer.go
test/e2e/addon/s3csidriver.go

Currently, we create pod identity association in each add-on and then delete the association when the add-on is deleted. That means every new add-on needs to have the same logic if it plans to use pod identity, resulting duplicate code.
Now we will handle pod identity association in `eks.CreateAddon` method. When `DeleteAddon` is called, the association will be removed as part of add-on deletion.
Tested with personal dev stack.

chore: Move pod identity association logic to addon.go

---

internal/containerd/install.go
internal/containerd/install_test.go
internal/containerd/sandbox.go
internal/containerd/sandbox_test.go
internal/containerd/version.go
internal/flows/install.go
internal/flows/upgrade.go
internal/packagemanager/packagemanager.go

Enables containerd `2.x` when available in the OS's package manager and K8s version is 1.30 or greater (the versions that have been tested for containerd 2.x - https://containerd.io/releases/). For now this is expected to the be AL2023 while RHEL 8/9 and Ubuntu 20/22/24 will remain on `1.7.x`. 
Containerd major version upgrading is enabled - customers previously on containerd `1.7.x` will also be upgraded to containerd `2.x` if available at upgrade time and compatible with the Kubernetes version.
There was a change in containerd config version from 2 to 3 as part of the containerd `2.x`. However the old config v2 is still compatible with containerd `2.x` (https://containerd.io/releases/#daemon-configuration), and the config will be …

Allow containerd 2.x for k8s versions >= 1.30

---

cmd/e2e-test/node/delete.go
test/e2e/peered/node.go

When running `node delete` to delete instances that are created by `node create`, it only deletes EC2 instance, leaving ssm instance orphaned. 
Now it deregisters ssm instance when the ec2 instance is deleted via `node delete`.
Tested manually

Deregister ssm instance when running node delete command

---

hybrid-nodes-cdk/lib/nodeadm/policies.ts

No smoke tests for secrets store csi driver addon
It adds necessary permissions for aws secrets manager. 
Tested manually. This is not fully tested in E2E because secrets store csi driver add-on is not publicly available yet. 

Add IAM permissions for secrets store csi smoke test

---

go.mod
go.sum
test/e2e/addon/secretsstorecsidriver.go
test/e2e/addon/testdata/secrets_store_csi_static_provisioning.yaml
test/e2e/cluster/cfn-templates/setup-cfn.yaml
test/e2e/suite/addon_ec2.go
test/e2e/suite/addons/addons_test.go
test/e2e/suite/peered_vpc.go

No smoke tests for secrets store csi driver addon
It validates secrets store csi driver functionality, assuming add-on is installed.
Tested manually. This is not fully functioning because secrets store csi driver add-on is not publicly available yet. 

Create smoke test for secrets store csi driver
